SIDM jeans profile
lenstronomy/lenstronomy pull request #264
Opened 2021-06-15 20:29 UTC by jhod0

Adds a model for the profile of Self-Interacting Dark Matter halos using the Jeans method modeling, following [Robertson 2021](https://github.com/sibirrer/lenstronomy.git) and [Sagunski 2021](https://github.com/sibirrer/lenstronomy.git).

The model is called `JEANS_ISO`. I have used it on my own machine and in low cross section limit it looks identical to NFW as expected, but I have not fully tested it.

This is a work in progress. TODOs:

- [ ] Fix inconsistent naming
- [ ] Examples
- [ ] Hessian of profile (currently only lensing potential and deflection are implemented)
- [ ] Tests
- [ ] Documentation

2021-06-15 20:44 UTC, sibirrer requested changes
Hi @jhod0 , thanks for this PR!
I think this is a valuable addition! I am waiting for updated documentation and tests for further review. I also ping @dangilman here in case he sees duplication or usefulness for his application as well.

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/Cosmo/lens_cosmo.py
> +        converts the physical mass, concentration, and velocity-weighted cross
can you also add to which model this corresponds/ can be used for?

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/Cosmo/lens_cosmo.py
> +        from astropy import units as u
perhaps some of these imports can be made at the file level to avoid a lot of (new) imports for every function call (if it becomes an issue)

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/jeans_iso.py
> +    Solves the Jeans method differential equation, and boundary conditions
perhaps some more documentation with context and references can be useful here

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/jeans_iso.py
> +    def hessian(self, *args, **kwargs):
if you don't find an analytic solution here, you can also do a numerical differentiation, as done for some other profiles as well

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/jeans_iso.py
> +    def set_static(self, **kwargs):
you don't need to add these as they are inherited from the base class (unless you want to allow some cache being saved that helps improve function calls for fixed parameters (i.e, could be useful when solving the lens equation)

2021-06-15 20:44 UTC, sibirrer commented on lenstronomy/LensModel/profile_list_base.py
> +        elif lens_type == 'JEANS_ISO':
the name is ok, but it does not indicate that in the outer parts, this is an NFW profile. Perhaps finding a (slightly) different name?

2021-06-15 20:58 UTC, jhod0 commented on lenstronomy/LensModel/Profiles/jeans_iso.py
> +    def set_static(self, **kwargs):
I had copied these over to remind myself if I wanted to implement them later. There is a lot of numerical integration in the potential/deflection implementations, so I am sure there is room for that kind of optimization!

2021-06-15 20:59 UTC, jhod0 commented
Thanks for the helpful comments Simon!

2021-06-15 21:33 UTC, dangilman commented
Hi @jhod0 and @sibirrer, it looks this pull request is related to adding a lens profile whose density is given by solving the radial Jeans equation out to r1 with the Kaplinghat et al. 2016 prescription. We just wrote a paper doing similar stuff so maybe I have provide some helpful input https://arxiv.org/pdf/2105.05259.pdf. My initial reaction is that you can do this in lenstronomy already if you write the Jeans modeling code and numerically integrate the deflection angles separately. You can store the relevant info in a class and pass it into lenstronomy using the profile NumericalAlpha defined in the numerical_deflections.py file. My other immediate reaction is that solving the Jeans equation and numerically integrating deflection angles each time might be prohibitively slow, but I guess this depends on how many deflection angles you need to compute

2021-06-15 22:27 UTC, jhod0 commented
Hi @dangilman, Yes that is exactly what this lens profile is for! This was partly inspired by your paper.

What you describe is pretty close to what this does: the `_JeansSolutionInterp` class solves the Jeans equation, stores interpolation tables, and solves the boundary conditions between the NFW and isothermal Jeans parts of the profile. The `SIDMJeans` class does the right integrations and analytical forms when it can to compute the potential and deflection angles. For generating mock images it is not prohibitively slow, I am able to generate the images below in seconds. (They show clusters with the r1 transition radius shown in orange, substructures added at green crosses). More complex things might be prohibitively slow

![image](https://user-images.githubusercontent.com/8944001/122130955-485e1280-cded-11eb-837b-a004f0594a67.png)

2021-06-16 15:09 UTC, dangilman commented
Hi @jhod0, cool sounds good! 

If your project requires deflection angles computed from the exact SIDM density profile rather than an approximation like cored NFW, that would be new and I suppose you need to the numerical integration in addition to the Jeans modeling. Whether or not all of that additional code belongs in lenstronomy versus a separate package I think is up to Simon and you. 

In our last paper about SIDM I tried to package the SIDM stuff separately from lenstronomy, you can check out the repo here: https://github.com/dangilman/SIDMpy. To avoid duplicating too much code, you could use it and add whatever routines you need, if you want.

2021-06-16 15:54 UTC, sibirrer commented
> Hi @jhod0, cool sounds good!
> 
> If your project requires deflection angles computed from the exact SIDM density profile rather than an approximation like cored NFW, that would be new and I suppose you need to the numerical integration in addition to the Jeans modeling. Whether or not all of that additional code belongs in lenstronomy versus a separate package I think is up to Simon and you.
> 
> In our last paper about SIDM I tried to package the SIDM stuff separately from lenstronomy, you can check out the repo here: https://github.com/dangilman/SIDMpy. To avoid duplicating too much code, you could use it and add whatever routines you need, if you want.

I am happy to have it included if it is tested and documented and useful for you @jhod0 . Best is to link also to Daniel's repo (and perhaps also the reference) to leave the user a range of options.

2021-06-16 18:46 UTC, jhod0 commented
Thanks for pointing me to SIDMpy - it looks a lot more general than what I have. I will continue the project I've been doing and judge how useful this would be.

2022-10-26 16:55 UTC, dangilman commented
hi @jhod0 we left off here a bit over a year ago. I'm wondering if there are any updates on your end and if you're still planning to add something to lenstronomy through this pull request?

2022-12-14 22:47 UTC, jhod0 commented
Hi @dangilman , apologies for the very late response. I did give up on this approach, as it was overly complicated and the isothermal solving was prohibitively slow. We can close this PR.

2022-12-15 21:08 UTC, dangilman commented
> Hi @dangilman , apologies for the very late response. I did give up on this approach, as it was overly complicated and the isothermal solving was prohibitively slow. We can close this PR.

Hi @jhod0, no problem, and OK, I will close this. For reference, if you're still interested in exploring this topic, I wrote some code that does the SIDM Jeans analysis (although I can't guarantee that it is fast enough for your project needs) https://github.com/dangilman/SIDMpy

2022-12-15 21:08 UTC, closed without merging