Feature/ifu grid galkin
lenstronomy/lenstronomy pull request #314
Opened 2022-04-11 02:17 UTC by ajshajib

Added some functions to `GalKin` to compute kinematics on an IFU grid and then convolve for PSF. Currently only the analytic computations have tests, will add the remaining tests later. 

@sibirrer, I created this PR for you to take a quick look and check if you are okay with the way I have added the functions, or you will prefer some other way to implement this feature. I will be updating this PR as I work on it to run the tests and check for coverage. I will notify you once this PR is ready for final review before merging.

2022-04-11 04:11 UTC, sibirrer commented
Hi @ajshajib, thanks a lot for this implementation! Yes, I am happy with how you added the functions into the existing design. Perhaps one aspect to check is that you performed an interpolation in IR directly in your new routine that perhaps interpolations that are currently made further down in the code might not be required since the evaluations of these functions are rather few in this new mode. But as long as numerically it is ok, there should not be a problem with that.

2022-08-05 16:19 UTC, sibirrer commented
@ajshajib there was also a failure of CI on the main branch and if you merge with main, the tests should pass

2022-08-05 17:23 UTC, ajshajib commented
@sibirrer, now a dynestry-related test is failing.

2022-08-05 17:29 UTC, sibirrer commented
brrr...this could either be a one-off (then we should set a random seed that it does not happen, or they have changed the settings to trigger a raise instead of a warning...

2022-09-03 18:07 UTC, sibirrer requested changes
Looks overall very good, thank you @ajshajib !
I have two minor comments. About formatting of code, your editor has a different formatting rule than what has been the default in lenstronomy (longer single lines) and this sometimes then causes PEP8 warnings on my PyCharm version. I 'think' I am using the astropy standard formatting conventions. Could you check whether you could use them, otherwise we see just a lot of changes in these files due to formatting rules and warnings, thanks!

2022-09-03 18:07 UTC, sibirrer commented on lenstronomy/Analysis/kinematics_api.py
>          :return: velocity dispersion [km/s]
I would specify a bit more the return products as they can deviate

2022-09-03 18:07 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +        self.numerics._lum_weight_int_method = True
this accesses a private method/variable of another class

2022-09-03 18:07 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +            np.sqrt((x_grid_supersampled-mass_center_x) ** 2 +
in these next lines, are you computing the radial distance twice? Perhaps define a variable that can be used multiple times to avoid duplication of calculations

2022-09-03 18:07 UTC, sibirrer commented on lenstronomy/GalKin/numeric_kinematics.py
> +        :return:
perhaps also add the return arguments here

2022-09-12 04:21 UTC, ajshajib commented on lenstronomy/GalKin/analytic_kinematics.py
> +    def _I_R_sigma2(self, R, kwargs_mass, kwargs_light, kwargs_anisotropy):
Needs testing.

2022-10-07 05:00 UTC, sibirrer commented
there is one check failing resulting in nan instead of a number

2022-10-07 05:03 UTC, ajshajib commented
Thanks, Simon! Actually the PR is not ready for your re-review. I sent out the commits to my personal fork just to have the newest commits synced to my hpc accounts through git. I will directly ask you when I think the PR is ready. 🙂

2022-10-07 05:04 UTC, sibirrer commented
ok. This PR might actually also help speed-up a bit the kinematics calculation for the milestone paper ;)

2022-10-07 05:06 UTC, ajshajib commented
Okay! Then, I should really get my act together and finally have this PR fully fleshed out. 😅

2022-10-10 21:02 UTC, ajshajib commented
> About formatting of code, your editor has a different formatting rule than what has been the default in lenstronomy (longer single lines) and this sometimes then causes PEP8 warnings on my PyCharm version. I 'think' I am using the astropy standard formatting conventions. Could you check whether you could use them, otherwise we see just a lot of changes in these files due to formatting rules and warnings, thanks!

Hi @sibirrer, can you kindly point me to the `astropy` standard conventions for me to see what to follow. I believe, my PyCharm is set to have max 79 characters per line, which is the PEP8 convention (https://peps.python.org/pep-0008/#maximum-line-length).

2022-10-10 21:07 UTC, sibirrer commented
> 
> Hi @sibirrer, can you kindly point me to the `astropy` standard conventions for me to see what to follow. I believe, my PyCharm is set to have max 79 characters per line, which is the PEP8 convention (https://peps.python.org/pep-0008/#maximum-line-length).

I see, from the astropy style guide: "Follow the existing coding style within a subpackage and avoid making changes that are purely stylistic. In particular, there is variation in the maximum line length for different subpackages (typically either 80 or 100 characters). Please try to maintain the style when adding or modifying code." So I guess then I set it =100 after that in PyCharm. So we can go with either way, as long as it's consistent per file

2022-10-10 21:09 UTC, ajshajib commented
Ok, got it!! I will set the line-length limit to 100 on my end too. :)

2022-10-10 21:47 UTC, ajshajib commented
Changes in this PR:

- Add functions in `Galkin` to compute IFU velocity dispersion in a grid, the PSF is convolved directly. Works for both numerical and analytical integration options, tested to match within 1% for power-law mass and Hernquist light profile.
- Add `IFU_grid` aperture type to allow the above functionality.
- Update `class KinematicsAPI` to allow accessing the IFU grid function from this class.
- Update `class TDCosmography` to allow accessing the updated functionalities in `class KinematicsAPI`.
- Update default numerical settings, generally set them to higher setting for higher accuracy in general purpose usage by default. If a user wants to gain in speed, then they can set the settings to appropriately low while maintaining required accuracy for their purpose. In that case, it's the user's responsibility to test for accuracy.

2022-10-10 21:59 UTC, ajshajib commented
As a note, I have tested `Galkin` vs `jampy`, and `jampy` computes the velocity dispersion profile systematically 2% lower for the same mass, light, and anisotropy profiles, even if the same MGEs are taken for mass and light. This may be due to differences in numerics in terms of integration limits and/or resolution, which I have not tested that exhaustively.

2022-10-10 22:00 UTC, ajshajib commented on lenstronomy/GalKin/numeric_kinematics.py
> +        :return:
Done.

2022-10-10 22:00 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +            np.sqrt((x_grid_supersampled-mass_center_x) ** 2 +
Done.

2022-10-10 22:00 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +        self.numerics._lum_weight_int_method = True
Fixed.

2022-10-10 22:01 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
>          :return: velocity dispersion [km/s]
Done.

2022-10-10 23:45 UTC, sibirrer requested changes
This looks very good, thank you @ajshajib ! I have some minor requests for better readability and structure of some of the code. I like the tests that you did a lot!
There seems to be a small decline in the test coverage. Might be worth looking at the latest coveralls report (it's in the same conversation box as the first one, they keep updating those)

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/Analysis/kinematics_api.py
> +        if self._analytic_kinematics:
I am a bit surprised of these added lines. Are the if - else statements exactly the same? And I would guess this part should rather be in the self.kinematic_lens_profile() definition if needed. Or am I missing something?

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/Analysis/kinematics_api.py
> +        :param r_eff: projected half-light radius of the stellar light associated with the deflector galaxy, optional, if set to None will be computed in this function with default settings THAT MAY
I am pretty sure this is longer than 100 characters :)

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/Analysis/kinematics_api.py
> +                kwargs_numerics_galkin = {'interpol_grid_num': 2000, # numerical interpolation, should converge -> infinity
am I understanding  correctly that between analytical and numerical default options, only the 'interpol_grid_num' number is different. Perhaps commenting in the code why you chose so might be helpful.

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/Analysis/kinematics_api.py
> +                kwargs_profile, kwargs_light, kwargs_anisotropy,
PEP8 can you re-format the lines that the input is after the start of the '('?

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/Analysis/td_cosmography.py
> +         :param direct_convolve: bool, if True, compute the 2D integral numerically
there is a space in here. Btw, you can type `$make docs` to test the rendering of the documentation or if there are errors or warnings occurring.

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/analytic_kinematics.py
> +        Get the maximum range of integration
minimum?

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +                raise ValueError("False for 'lum_weight_int_method' is not supported!")
hmm, are luminosity-weighting not supported? This might be needed when the PSF is large and the light and kinematic profile non-uniform

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +        if not isinstance(kwargs_mass, dict):
these are quite some lines of code that are not so tight to the functionality. Perhaps can you write those in a util function? Or can you make a requirement on the input that needs to be satisfied? Also, is it correct that it would work when mass and light center are not aligned?

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +        sigma2_grid = sigma_IR_integrated / IR_integrated
this line seems to suggest that the calculation is done luminosity weighted.

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/galkin_model.py
> +                kwargs_numerics = {'interpol_grid_num': 2000,  # numerical interpolation, should converge -> infinity
these seem rather duplicated default options to the SimulationAPI. It's just a matter of taste I think for how many layers of default options we want in the code

2022-10-10 23:45 UTC, sibirrer commented on lenstronomy/GalKin/numeric_kinematics.py
> +        Get the maximum range of integration
minimum?

2022-10-10 23:45 UTC, sibirrer commented on test/test_Analysis/test_kinematics_api.py
> +        Galkin.
could you perhaps in out-commented way include the script how jampy was executed, for prosperity?

2023-04-24 14:05 UTC, sibirrer commented
Hi @ajshajib , just checking on this PR. I can also make a simpler version of radial bins which is effectively a 1d calculation. That's all what I currently need for my project

2023-04-24 14:24 UTC, ajshajib commented
@sibirrer, please go ahead with implementing the 1D version. It would be more efficient, I think, to implement it directly than using the 2D case for convolution and then taking a 1D slice.

2023-12-13 17:34 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +                kwargs_profile, kwargs_light, kwargs_anisotropy,
Resolved.

2023-12-13 17:46 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +        :param r_eff: projected half-light radius of the stellar light associated with the deflector galaxy, optional, if set to None will be computed in this function with default settings THAT MAY
Fixed.

2023-12-13 17:47 UTC, ajshajib commented on lenstronomy/Analysis/td_cosmography.py
> +         :param direct_convolve: bool, if True, compute the 2D integral numerically
Fixed.

2023-12-13 17:47 UTC, ajshajib commented on lenstronomy/GalKin/numeric_kinematics.py
> +        Get the maximum range of integration
Fixed.

2023-12-13 17:49 UTC, ajshajib commented on lenstronomy/GalKin/analytic_kinematics.py
> +        Get the maximum range of integration
Fixed.

2023-12-14 03:20 UTC, ajshajib commented on test/test_Analysis/test_kinematics_api.py
> +        Galkin.
Done.

2023-12-14 03:26 UTC, ajshajib commented on lenstronomy/GalKin/galkin_model.py
> +                kwargs_numerics = {'interpol_grid_num': 2000,  # numerical interpolation, should converge -> infinity
Removed similar settings applied from `KinematicsAPI`.

2023-12-14 09:16 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +        if not isinstance(kwargs_mass, dict):
Moved the lines to a new function. And, yes, it would work if mass and light are misaligned in the provided `kwargs`.

2023-12-14 09:18 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +        sigma2_grid = sigma_IR_integrated / IR_integrated
Yes, do you suggest any alternative?

2023-12-14 09:19 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +                kwargs_numerics_galkin = {'interpol_grid_num': 2000, # numerical interpolation, should converge -> infinity
Reverted back `'interpol_grid_num'` to 200 after running some tests, but set `'min_integrate'` to 1e-4.

2023-12-14 09:41 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +        if self._analytic_kinematics:
Moved out the codes from here and made it tidier.

2023-12-14 09:42 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +        sigma2_grid = sigma_IR_integrated / IR_integrated
That's right, but you have any other suggestion?

2023-12-14 13:06 UTC, sibirrer requested changes
Thank you very much @ajshajib ! This looks very good. I also like the tests against jampy. I have some more minor suggestions for documentation and perhaps splitting up one function.

2023-12-14 13:06 UTC, sibirrer commented on lenstronomy/GalKin/galkin.py
> +    def dispersion_map_grid_convolved(
this is quite a long definition. Is it possible to split it a bit up for better readability and perhaps better testing?

2023-12-14 13:06 UTC, sibirrer commented on lenstronomy/Util/util.py
> +        print(numPix)
do you need this print statement?

2023-12-14 17:56 UTC, ajshajib commented on lenstronomy/GalKin/analytic_kinematics.py
> +        """
Done.

2023-12-14 17:56 UTC, ajshajib commented on lenstronomy/GalKin/analytic_kinematics.py
> +        a = cls._get_a(kwargs_light)
Yes. `cls` is the same as `self`, but the standard variable name for a class method.

2023-12-14 17:57 UTC, ajshajib commented on lenstronomy/GalKin/analytic_kinematics.py
`cls` is the same as `self`, but it is the standard variable name used for a class method.

2023-12-14 17:58 UTC, ajshajib commented on lenstronomy/Util/util.py
> +        print(numPix)
No, this was left over from debugging, thanks for catching! Fixed.

2023-12-14 22:56 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +        :param get_IR_map: if True, will return the pixelized IR maps to use for Voronoi
Removed the return of the IR map. My initial thought was if people wanted to change their own Voronoi binning in post-processing from the regular grid without needing to recompute the whole dispersion map. But, keeping it simple for now.

2023-12-14 22:56 UTC, ajshajib commented on lenstronomy/Analysis/kinematics_api.py
> +            sigma_v_map = galkin.dispersion_map_grid_convolved(
Removed returning the `IR_map`.

2023-12-14 22:57 UTC, ajshajib commented on lenstronomy/GalKin/galkin.py
> +    def dispersion_map_grid_convolved(
Broken down the function in smaller functions and added tests for each.

2023-12-14 23:01 UTC, ajshajib commented
@sibirrer, thanks a lot for the review comments. I have responded to them and made the appropriate changes.

2023-12-15 01:18 UTC, sibirrer approved these changes

2023-12-15 01:19 UTC, merged