Allow sampling distance ratios in multi-lens-plane and multi-source-plane setting
lenstronomy/lenstronomy pull request #318
Opened 2022-04-27 19:17 UTC by ajshajib

2022-04-27 19:31 UTC, ajshajib commented
@sibirrer, this PR is not ready to be merged yet. I created the PR to check with you if the way I am implementing this feature looks fine to you. I am yet to add relevant tests and debug.

I have added `a` and `b` distance ratio parameters in `kwargs_special`. The update of the relevent `T_ij` parameters are then within `Image2SourceMapping` class, since it's cleaner to do all the updates at the same place related to both the lens planes and the source planes. Now, the distance updates become complicated within my formulation of `a` and `b` parameters, when there are intermediate source planes with no deflector defined on it. So, I added a lens profile called `BLANK_PLANE`, so a user needs to add this blank planes in the lens model list corresponding to any intermediate source plane without a deflector. In this way, all the `T_ij`s are easy to keep track of. Let me know if you are happy with this workflow in the code for this feature. Most of the changes is done in `image2source_mapping.py`, so take a look at this file specifically.

2022-04-27 19:51 UTC, ajshajib commented
@sibirrer, I see that you actually changed a bunch of calls to `ray_shooting_partial()` to `ray_shooting_partial_comoving()` in [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6). I thought, it was me that did it through an accidental refactoring of the function name, so I changed them back to match with the current main branch. Are those changes still necessary in the current implementation of the feature? If so, I can edit them back in to match with [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6).

2022-04-27 19:54 UTC, sibirrer commented
> @sibirrer, I see that you actually changed a bunch of calls to `ray_shooting_partial()` to `ray_shooting_partial_comoving()` in [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6). I thought, it was me that did it through an accidental refactoring of the function name, so I changed them back to match with the current main branch. Are those changes still necessary in the current implementation of the feature? If so, I can edit them back in to match with [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6).

Hi @ajshajib, I made the changes to be more explicit to be in coming coordinates. The reason is that I am experimenting on another branch on having the multi-plane formalism in different units (currently, it only works for flat background cosmologies where the comoving ray-tracing works fine, but for curved background cosmologies, there are some issues with the current implementation)

2022-04-27 23:22 UTC, sibirrer requested changes
Thanks @ajshajib for the PR. I like the approach moving all these aspects to the image2source mapping such that other modules are as untouched as possible.

Since this feature is rather complex, it is important to have a good documentation of it, such that if we refactor it later, we still know what it does.

I just put some other comments in this review knowing that it's not ready to be reviewed but that I found when going through the code.

Thanks a lot!

2022-04-27 23:22 UTC, sibirrer commented on lenstronomy/LensModel/MultiPlane/multi_plane.py
> +            T = self._multiplane._D_z_list_fiducial[ind]
is T_z the same as D_z? I am not sure where this change comes from

2022-04-27 23:22 UTC, sibirrer commented on lenstronomy/Sampling/special_param.py
> +            self._D_dt_sampling = False
or can you put in raise statements in here instead, such that the user realizes that you can not sample the distance ratios and redshifts at the same time and the current options chosen are not valid?

2022-04-27 23:22 UTC, sibirrer commented on lenstronomy/LensModel/MultiPlane/multi_plane_base.py
> +    def z_source_convention(self):
here it would be great having description for all the public definitions

2022-04-27 23:22 UTC, sibirrer commented on lenstronomy/ImSim/image2source_mapping.py
> +class MultiPlaneOrganizer(object):
this should probably be in another file

2022-04-28 00:37 UTC, ajshajib commented on lenstronomy/LensModel/MultiPlane/multi_plane.py
> +            T = self._multiplane._D_z_list_fiducial[ind]
T_z is not the same as D_z, the intended relation is T_z = D_z * (1+z). This was probably changed by an automatic refactoring and is unintended. I will fix it, thanks for catching this.

2022-04-28 00:39 UTC, ajshajib commented
> Since this feature is rather complex, it is important to have a good documentation of it, such that if we refactor it later, we still know what it does.

Yes, I will add as much documentations as possible at appropriate places. Thanks for the other pointers in the code. 🙂

2022-05-03 17:40 UTC, ajshajib commented
> Hi @ajshajib, I made the changes to be more explicit to be in coming coordinates. The reason is that I am experimenting n another branch on having the multi-plane formalism in different units (currently, it only works for flat background cosmologies where the comoving ray-tracing works fine, but for curved background cosmologies, there are some issues with the current implementation)

Hi @sibirrer, it looks to me that the commit [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6) doesn't retain the appropriate multi-plane behavior as the main branch. Is it already known? I have tested with a model that works with the main branch, but the best fit model doesn't work if I use [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6) after pulling the current main branch into it (I needed to pull the current main branch so that the notebook works with currently installed scipy versions etc). For the free distances feature, I intended to leave the default behavior untouched and the new behavior to be turned on only with `distance_ratio_sampling = True`. However, since the default behavior after [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6) looks broken, I'm unsure about how to go on with debugging and testing.

2022-05-03 18:46 UTC, sibirrer commented
HI @ajshajib, hmm, you can also rename the main branch partial ray-tracing to be explicitly '_comoving' and then it should work. I think I have started on the multi-plane development branch but did not merge these conventions. You can also ignore and follow the main branch for your feature and then we/I can adopt it later on. I would focus this PR to only implement one feature enabling the distance ratio sampling and then, once merged, perhaps tackle another thing, if this works and makes sense.

2022-05-03 18:53 UTC, ajshajib commented
> HI @ajshajib, hmm, you can also rename the main branch partial ray-tracing to be explicitly '_comoving' and then it should work. I think I have started on the multi-plane development branch but did not merge these conventions. You can also ignore and follow the main branch for your feature and then we/I can adopt it later on. I would focus this PR to only implement one feature enabling the distance ratio sampling and then, once merged, perhaps tackle another thing, if this works and makes sense.

Probably changing the main branch partial ray-tracing to be explicitly '_comoving' is a quicker fix now? Can you kindly point out which line of code you're talking here? I think, reverting the all the conventions to the main branch may be a bit cumbersome as I see that there are numerous small code changes here and there in commit [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6).

2022-05-03 19:03 UTC, sibirrer commented
@ajshajib which error in the test are you talking? Looking at the test failings, it has to do with 

num_lens_planes = len(list(set(self._lens_redshift_list)))
[7674](https://github.com/sibirrer/lenstronomy/runs/6278720698?check_suite_focus=true#step:5:7674)
E       TypeError: 'NoneType' object is not iterable

Which is a change that all default initializations of the class parameters are =None (instead of empty lists). This is not part of  the commit you stated. You can simply make an option that if lens_redshift_list is None: lens_redshift_list = [] to get back the same behavior

2022-05-03 19:11 UTC, ajshajib commented
@sibirrer, I am not looking at the tests yet. I was simply checking out a best fit lens model. For example, this is a model fitted with the main branch:
![image](https://user-images.githubusercontent.com/20169048/166525274-bcc7ef2a-c681-4f3a-91f5-be2cb6715db2.png)

And, this is what the model plot looks like with commit [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6): 
![image](https://user-images.githubusercontent.com/20169048/166524913-d31b4160-0e2c-43cc-a436-701b40589edd.png)

2022-05-03 20:09 UTC, sibirrer commented on lenstronomy/ImSim/image2source_mapping.py
> +                x_source, y_source = np.zeros_like(x), np.zeros_like(y)
@ajshajib  it might be this line as x_source should be beta_x (then angular coordinate on the sky of the position of the light ray 

Unfortunately I have not made test functions between new and old implementation so it's hard to check

2022-05-03 20:16 UTC, sibirrer commented on lenstronomy/ImSim/image2source_mapping.py
> +                x_source, y_source = np.zeros_like(x), np.zeros_like(y)
hmm, I really have only one potential idea. And that commit you linked is the only difference in the source code? Just checking for myself...

2022-05-04 00:08 UTC, ajshajib commented on lenstronomy/ImSim/image2source_mapping.py
> +                x_source, y_source = np.zeros_like(x), np.zeros_like(y)
Yes, this issue occurs right at the commit [4b6a6c4](https://github.com/sibirrer/lenstronomy/pull/318/commits/4b6a6c45b4842166b54134707e3f3f17f7de3ce6).

2022-05-04 05:36 UTC, sibirrer commented on lenstronomy/LensModel/MultiPlane/multi_plane.py
@ajshajib in the LensedLocation class there is another ray_shooting_partial() call that needs to be re-named to ray_shooting_partial_comoving() that I forgot. I think it's line #365 in multi_plane.py

2023-11-24 21:07 UTC, ajshajib commented on lenstronomy/ImSim/image2source_mapping.py
> +class MultiPlaneOrganizer(object):
Done.

2023-11-24 21:36 UTC, ajshajib commented on lenstronomy/LensModel/MultiPlane/multi_plane_base.py
> +    def z_source_convention(self):
Done.

2023-11-24 21:36 UTC, ajshajib commented on lenstronomy/Sampling/special_param.py
> +            self._D_dt_sampling = False
Done.

2023-11-26 03:21 UTC, ajshajib commented on lenstronomy/LensModel/Solver/lens_equation_solver.py
> +                "Instance of lens_model passed to this class does not compute the lensing potential, "
```suggestion
                "Instance of `LensModel` passed to this class does not compute the lensing potential, "
```

2023-11-26 03:23 UTC, ajshajib commented on lenstronomy/PointSource/Types/base_ps.py
> +        :return: internal lens_model class updated
```suggestion
        :return: internal `LensModel` class updated
```

2023-11-26 03:24 UTC, ajshajib commented on lenstronomy/SimulationAPI/model_api.py
> +        :return: kwargs_lens in reduced deflection angles compatible with the lens_model instance of this module
```suggestion
        :return: kwargs_lens in reduced deflection angles compatible with the `LensModel` instance of this module
```

2023-11-26 05:28 UTC, ajshajib commented on test/test_LensModel/test_Profiles/test_blank_plane.py
> +    """Class to test the Moffat profile."""
```suggestion
    """Class to test the "BLANK_PLANE" lens model."""
```

2023-11-26 14:16 UTC, sibirrer approved these changes
Looks really good, thank you very much! I have two minor comments. Other than that ready to go

2023-11-26 14:16 UTC, sibirrer commented on lenstronomy/ImSim/multiplane_organizer.py
> +            raise ValueError("z_lens_convention needs to be the first lens " "plane!")
do you want to do the raise testing?

2023-11-26 14:16 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/blank_plane.py
> +    This is needed to a create a blank plane that has a source without any lensing
typo 'to a...'

2023-11-26 14:16 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        # :param distance_ratio_sampling: bool, if True, samples the distance ratios in multi-lens-plane,
does this has to be out commented? Just checking

2023-11-26 16:38 UTC, ajshajib commented on lenstronomy/ImSim/multiplane_organizer.py
> +            raise ValueError("z_lens_convention needs to be the first lens " "plane!")
Done.

2023-11-26 16:38 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/blank_plane.py
> +    This is needed to a create a blank plane that has a source without any lensing
Fixed.

2023-11-26 16:39 UTC, ajshajib commented on lenstronomy/Sampling/parameters.py
> +        # :param distance_ratio_sampling: bool, if True, samples the distance ratios in multi-lens-plane,
Removed this line as `distance_ratio_sampling` is not directly provided to the `Param` class, but inside the passed `kwargs_model`.

2023-11-26 16:43 UTC, ajshajib commented
@sibirrer, thanks a lot for the quick review! I have fixed the minor issues you pointed out. I will merge after the tests pass. Cheers!

2023-11-26 17:07 UTC, merged