General parameter scaling
lenstronomy/lenstronomy pull request #350
Opened 2022-08-22 21:18 UTC by jhod0

# General parameter scaling

This is an implementation of a feature I have discussed with Simon and Anowar. I added a few tests which pass but have not played with it too much yet.

It also includes a small refactor of how parameters are handled, which made it easier for me to implement this. The interface remains the same.

## Explanation

I am working on modeling lensing galaxy clusters and would like to fit the member mass profiles together in a uniform way, scaling their overall mass and radius by their magnitude. Something similar to these equations from [Bergamini 2019](https://ui.adsabs.harvard.edu/abs/2019A%26A...631A.130B/abstract):

![image](https://user-images.githubusercontent.com/8944001/186019141-2f8db310-7e84-4f39-8491-07cdb27b210a.png)

The existing `mass_scaling` parameter is similar but not exactly what I need; it only scales the overall mass linearly.

This PR implements generalized scaling, where any lens parameter can be scaled like this::

```
kwargs_lens[i]['param'] = param_scale * kwargs_lens[i]['param'] ** param_power
```

Where both `param_scale` and `param_power` can be fixed or sampled.

## Use

The interface is similar to `mass_scaling`, a mask is provided for each scaled parameter listing which lenses will be scaled.

This example will scale the `sigma0` and `Rs` parameters of `PJAFFE` profiles, like in the Bergamini example above. The member lens masses are labeled with `1`.

```
kwargs_constraints = {
    'general_scaling': {
        'sigma0': [False]*num_halo + [1]*nmembers,
        'Rs': [False]*num_halo + [1]*nmembers,
    }
}
```

And the initial values and bounds can be provided like this. This fixes the power-law exponent but varies the overall scaling for both `sigma0` and `Rs`.

```
fixed_special = {'sigma0_scale_pow': [alpha*2], 'Rs_scale_pow': [beta]}
kwargs_special_init = {'sigma0_scale_factor': [17.0], 'Rs_scale_factor': [8]}
kwargs_special_sigma = {'sigma0_scale_factor': [10.0], 'Rs_scale_factor': [3]}
kwargs_lower_special = {'sigma0_scale_factor': [0.5], 'Rs_scale_factor': [1]}
kwargs_upper_special = {'sigma0_scale_factor': [40], 'Rs_scale_factor': [20]}

special_params = [kwargs_special_init, kwargs_special_sigma, fixed_special, kwargs_lower_special, kwargs_upper_special]
```

2022-08-22 21:46 UTC, sibirrer commented
Hi @jhod0 , this looks great and an overall improvement of the style of parameter handing with a neat feature added.
The tests are failing because relative imports are apparently not supported to that level with '..', see error message.

- Can you add a test function for each class and give a description of the meaning of each class in words as doc strings?
- Is it possible for you to add about the same description for the use case as you nicely laid out in this issue in the doc strings of the Param() class? (or where you find it best suited)

Once the documentation of your current design is there, I have it easier to go through the code line-by-line for more minor things.

Thank you very much!

2022-08-22 23:44 UTC, jhod0 commented
Great, thanks Simon!

I have fixed the failing test and added docstrings for each of the new classes, and a blurb in the `Param` class similar to what I wrote in this post.

I have added a new test file for the abstract classes implemented in `Sampling/param_group.py`.

Let me know if you think this needs more documentation or other tweaks!

2022-08-23 04:49 UTC, sibirrer requested changes
All in all looks very good. I am a bit stingy with documentation (more and more with every added feature) also such that the documentation looks good. You can test out the sphinx auto-generated documentation with 
>>> $make docs
(when you are in the base lenstronomy repo where the make file is and you have installed the sphinx extensions)

I would like another review by @ajshajib  to follow best practices with multiply eyes on the code (you are the ginny pig here...)

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/PointSource/point_source_param.py
> +        self.on = int(num_images) > 0
can you document the variable num_images in doc strings?

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/PointSource/point_source_param.py
> +class PointAmp(ArrayParam):
I would re-name this class to ImageAmp as it means the amplitude of the point source as seen in the image. I want to re-name this variable and there is actually a PR for this. But perhaps re-naming the class first is a step in the direction

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/PointSource/point_source_param.py
> +    Point amplification, possibly many
here the description should be 'amplitude of the point source as seen in the image' or something along these lines

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/PointSource/point_source_param.py
> +    def __init__(self, fixed_magnification):
please describe the variable fixed_magnification in the docstring

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/PointSource/point_source_param.py
> +                for grp in model_params:
'grp' as a variable does not have much meaning for me. Can you re-name it to something a bit more obviously meaningful?

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/param_group.py
> +        returns: 2-tuple of (num param, list of names)
the sphinx convention is :returns:

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/param_group.py
> +class ModelParamGroup:
in this class, many input arguments are not documented. Use 
>>> :param <variable_name>: blabla
>>> :type <variable_name>: python type

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/param_group.py
> +class SingleParam(ModelParamGroup):
please make docstrings for input and output variables

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        'sigma0': [False]*num_halo + [1]*nmembers,
I would simplify the example. 'num_halo' and 'nmembers' are not really defined nor strictly necessary.
I guess currently there is no raise statement when the parameter in question (i.e. 'sigma0' in this example) is not part of the parameters for the model that is set to [True]. Perhaps make a TODO note that this is perhaps desired in the future

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +    ```
in the PR, you had a screen shot of the scaling law. Would you mind typing it down in latex here.

For docstrings, use

.. math::

  \\sigma_{0} = a^b

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +    ```
make sure you use '\ \\' as one '\\' gets cut short

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +                 # General scaling: need names of params and number of individual params
can you add the description of the parameter further down with :param general_scaling:?

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        if self._mass_scaling:
we could think of even fully removing mass_scaling and replace it with something within the power_law scaling that automatically sets the power=1. You don't need to do it, but perhaps mark a TODO item in the code, or even a DeprecationWarning that this will come.

2022-08-23 04:49 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        # TODO print settings of specailParams?
Yes, if you want to, that would be great. I have neglected this print statements a bit...

2022-08-23 04:52 UTC, sibirrer commented
oh, and add your name and link to your GitHub page in the AUTHORS.rst file :)

2022-08-23 17:56 UTC, jhod0 commented on lenstronomy/Sampling/parameters.py
> +        if self._mass_scaling:
that makes a lot of sense, I thought about having the general_scaling default the power law index to 1 as well. I decided not to because it could cause confusion, if for instance someone provides the power law index with a typo and lenstronomy silently defaults to 1. I think reimplementing mass_scaling to use the same machinery as general_scaling makes most sense. I am adding a TODO along these lines

2022-08-23 18:07 UTC, jhod0 commented on lenstronomy/Sampling/parameters.py
> +        # TODO print settings of specailParams?
I am leaving this as a TODO because I am not sure how best to display the information. the special params grouping is a bit eclectic and I am not sure what all of the options mean

2022-08-23 19:05 UTC, sibirrer reviewed
Looks very good and thank you very much for the added documentation!
I have some very minor comments left and that's it from my side. I leave it then for Anowar to glance over it in case

2022-08-23 19:05 UTC, sibirrer commented on lenstronomy/Sampling/param_group.py
> +    def set_params(self, kwargs, kwargs_fixed):
there are still a few routines without doc strings...sorry for being pedantic :)

2022-08-23 19:05 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        if self._mass_scaling:
ok, we can leave it like the and thanks for marking it as TODO

2022-08-23 19:05 UTC, sibirrer commented on lenstronomy/Sampling/parameters.py
> +        # TODO print settings of specailParams?
I was just thinking you add the print statement of the option you are implementing. I don't want to blame you for code that is already there, just want to make sure that new features being implemented get added and generally improve the usability

2022-08-23 19:24 UTC, jhod0 commented
No problem, I appreciate the extra care to make lenstronomy great!

For some reason I can't reply above, but I think `fixed_magnification` is an integer. This is a snippet of how it was implemented before, where the `point_amp` parameter is set to an array.

Maybe I am misunderstanding what the intention was. In any case, the array was the reason I implemented `ImageAmp` as an `ArrayParam` subclass

https://github.com/lenstronomy/lenstronomy/blob/1e6d9311bed4e4af19f62df965e8d9ad4fc54f0e/lenstronomy/PointSource/point_source_param.py#L45-L48

2022-08-23 20:01 UTC, sibirrer commented
> No problem, I appreciate the extra care to make lenstronomy great!
> 
> For some reason I can't reply above, but I think `fixed_magnification` is an integer. This is a snippet of how it was implemented before, where the `point_amp` parameter is set to an array.
> 
> Maybe I am misunderstanding what the intention was. In any case, the array was the reason I implemented `ImageAmp` as an `ArrayParam` subclass
> 
> https://github.com/lenstronomy/lenstronomy/blob/1e6d9311bed4e4af19f62df965e8d9ad4fc54f0e/lenstronomy/PointSource/point_source_param.py#L45-L48

'fixed_magnification' is a list of booleans for each point source model to state whether the image amplitudes are fixed in respect to the source amplitude through the lensing magnification, or instead treated as stand-alone independent amplitude parameters. If the argument is true, it uses one 'source_amp' parameter, and if the argument is False, it uses the length of image positions as the argument.

2022-08-23 20:26 UTC, jhod0 commented
OK, I have confused myself a little, and I was using the fixed_magnification correctly, but here is my understanding:

- if the magnification is fixed, a single parameter `source_amp` is sampled per point source model
  - this corresponds to the SourceAmp class I have defined
- if the magnification is not fixed, `num_point_sources` are sampled, one for each point source
  - this corresponds to the ImageAmp class I have defined

I think my implementation was correct but the naming was wrong. I have changed the name and documentation accordingly

https://github.com/lenstronomy/lenstronomy/blob/1e6d9311bed4e4af19f62df965e8d9ad4fc54f0e/lenstronomy/PointSource/point_source_param.py#L102-L113

https://github.com/lenstronomy/lenstronomy/blob/1e6d9311bed4e4af19f62df965e8d9ad4fc54f0e/lenstronomy/PointSource/point_source_param.py#L180-L188

2022-08-23 20:28 UTC, sibirrer approved these changes
Great, I approve this PR. @ajshajib  should also have a look at it.

2022-08-23 21:40 UTC, ajshajib commented on AUTHORS.rst
> -* Andreas Filipp `andreasfilipp <https://github.com/andreasfilipp/>`_
Why was Andreas Filipp removed?

2022-08-23 21:42 UTC, sibirrer commented on AUTHORS.rst
> -* Andreas Filipp `andreasfilipp <https://github.com/andreasfilipp/>`_
I think he was moved as not alphabetically ordered

2022-08-23 21:43 UTC, ajshajib commented on AUTHORS.rst
> -* Andreas Filipp `andreasfilipp <https://github.com/andreasfilipp/>`_
O, alright.

2022-08-23 21:49 UTC, jhod0 commented on AUTHORS.rst
> -* Andreas Filipp `andreasfilipp <https://github.com/andreasfilipp/>`_
I just moved them up in the list to keep alphabetic order! Certainly not trying to remove their credit haha. Andreas now appears after Sydney Erickson

2022-08-23 21:54 UTC, ajshajib commented on lenstronomy/Sampling/param_group.py
> +    def __init__(self, on):
I suggest to add a docstring for `on`. Also, if `self.on` is only intended to be used within this class instance itself, I recommend to rename the variable to `self._on`, `_` flags that it's a "private" variable.

2022-08-23 21:54 UTC, ajshajib commented on lenstronomy/Sampling/param_group.py
> +        Tells the number of parameters that this group samples and theri names.
theri → there

2022-08-23 22:06 UTC, jhod0 commented on lenstronomy/Sampling/param_group.py
> +        Tells the number of parameters that this group samples and theri names.
done, thanks!

2022-08-23 22:07 UTC, jhod0 commented on lenstronomy/Sampling/param_group.py
> +    def __init__(self, on):
I have refactored this as a read-only variable like you suggested. All the subclass initializers changed accordingly

2022-08-23 23:25 UTC, ajshajib approved these changes
This looks good to me. Thanks @jhod0 for making the requested changes, and also for making this very helpful PR. I am looking forward to using this for some of my group-scale lenses. 😊

2022-08-23 23:26 UTC, merged