Line of sight effects
lenstronomy/lenstronomy pull request #363
Opened 2022-09-12 12:37 UTC by nataliehogg

Implementation of the line of sight effects as described in [Fleury et al. (2021)](https://arxiv.org/abs/2104.08883).

2022-09-12 18:40 UTC, sibirrer requested changes
Thank you for the PR of this very nice feature!
I have primary minor requests on documentations (which is already very good with all the latex formulae!!)
Please also look at the test coverage and perhaps there are some untested lines of code. Quite some tests are against numerical values that I don't know where they come from. Are there some special cases where they are known and easy to test against?

I let @dangilman do the review, approval and merge, if this is ok.

2022-09-12 18:40 UTC, sibirrer commented on test/test_LensModel/test_LineOfSight/test_single_plane_los.py
> +        assert output == 0.77880078307140488/(8*np.pi)
I would allow some numerical imprecision for all these tests. You can use numpy.testing and there are routines like assert_almost_equal() where you can also define a decimal precision statement. It could happen that some underlying numerics are being changes (even in scipy or numpy) that might cause these tests to fail in the future by one or two digits.

2022-09-13 08:46 UTC, nataliehogg commented on lenstronomy/LensModel/profile_list_base.py
> +                     'LOS', 'LOS_MINIMAL',
We created a sheared EPL profile at the beginning of the implementation for testing purposes but it's not needed any more so I have removed all references to EPL_SHEARED along with the profile itself.

2022-09-13 08:46 UTC, nataliehogg commented on lenstronomy/LensModel/lens_model.py
> -        :param x_source: source position (optional), otherwise computed with ray-tracing
Thanks, I think this probably got omitted by mistake so I've added it back in.

2022-09-13 08:47 UTC, nataliehogg commented on lenstronomy/LensModel/MultiPlane/multi_plane_base.py
> +
Thanks, removed.

2022-09-13 09:03 UTC, nataliehogg commented on lenstronomy/LensModel/LineOfSight/LOSModels/los.py
> +    def distort_vector(self, x, y, kappa=0, gamma1=0, gamma2=0, omega=0):
Done, thanks.

2022-09-13 09:16 UTC, nataliehogg commented on test/test_LensModel/test_LineOfSight/test_single_plane_los.py
> +        assert output == 0.77880078307140488/(8*np.pi)
Sure, I already had to change the test_mass_2d function from assert to assert_almost_equal in order to make it pass, so I can easily change the rest. Is there a certain level of precision you would like?

2022-09-13 09:20 UTC, nataliehogg commented
Thanks for the very helpful comments @sibirrer. Regarding the tests which use hardcoded numerical values, I actually took those directly from test_single_plane.py, as I wanted to repeat those tests using our SinglePlaneLOS class with zero shear (so they should give the same result). Would you prefer it if I figured out a different case to compare with? Arguably the most important test is test_los_versus_multiplane, which doesn't rely on hardcoded numbers. However, it does use astropy, so should I add that to the test_requirements.txt?

I had a look on coveralls to see if I could see exactly which new lines remain untested but it says "source not available". Is that a bug? (I haven't used coveralls before). I think I can add a test for the Fermat potential/time delays which should boost the coverage anyway.

Of course we are very happy for @dangilman to do the review.

2022-09-13 14:54 UTC, sibirrer commented on test/test_LensModel/test_LineOfSight/test_single_plane_los.py
> +        assert output == 0.77880078307140488/(8*np.pi)
ah I see :). Perhaps better, instead of testing with the numerical values, is directly testing against SinglePlane.

Hmm, seems strange with coveralls. I hope it's temporarily.

2022-09-13 16:35 UTC, nataliehogg commented on test/test_LensModel/test_LineOfSight/test_single_plane_los.py
> +        assert output == 0.77880078307140488/(8*np.pi)
hi again @sibirrer the tests now compare with SinglePlane directly rather than with hardcoded numbers. The bug I mentioned above is now fixed too.

2022-09-13 21:01 UTC, dangilman requested changes
Hi, everything looks good to me. The only minor comments I have are related to a couple variables/classes defined inside of other classes that seem like they should be private with an underscore. Also, do you know which lines of code are responsible for the drop in test coverage?

2022-09-13 21:37 UTC, sibirrer approved these changes
I approve and let @dangilman merge it once his comments are addressed. Thank you!

2022-09-14 10:13 UTC, nataliehogg commented on lenstronomy/LensModel/LineOfSight/single_plane_los.py
> +        self.main_lens = SinglePlane(lens_model_list_wo_los,
Changed, thanks.

2022-09-14 10:13 UTC, nataliehogg commented on lenstronomy/LensModel/LineOfSight/single_plane_los.py
> +        self.los_model = lens_model_list[index_los]
Done.

2022-09-14 10:30 UTC, nataliehogg commented
Hi @dangilman thanks for your comments. I think it's fine for the variables and class to be private, so I've changed them accordingly.

Regarding the coverage, coveralls is not working so I can't see which lines are missing coverage (it just says "source not available"). I'll try to work it out anyway, but perhaps the problem with coveralls is on the lenstronomy side rather than mine?

2022-09-14 16:02 UTC, merged