Model plot fix
lenstronomy/lenstronomy pull request #381
Opened 2022-10-31 15:58 UTC by sibirrer

This pull request should fix bug #380 for at least a single band. A new routine to extract the 'amp' parameters from the kwargs_list was required.

2022-10-31 15:59 UTC, sibirrer commented
@ajshajib I still need to add some test functions. But let me know if you see issues/concerns in the meantime

2022-10-31 18:06 UTC, sibirrer commented
ok, @ajshajib , ready for review :)

2022-11-02 06:07 UTC, ajshajib commented on lenstronomy/Plots/model_plot.py
>          model, error_map, cov_param, param = self._imageModel.image_linear_solve(inv_bool=True, **kwargs_params)
Lines 53-56 needs to be changed like the code below to make the new changes to work.

```
        kwargs_params_copy = copy.deepcopy(kwargs_params)
        model, error_map, cov_param, param = self._imageModel.image_linear_solve(inv_bool=True, **kwargs_params)

        if linear_solver is False:
            if len(multi_band_list) > 1:
                raise ValueError('plotting the solution without the linear solver currently only works with one band.')

            kwargs_params = kwargs_params_copy
```

2022-11-02 15:27 UTC, ajshajib requested changes
Hi @sibirrer, thanks a lot for implementing the fix! In my test, it's still not fully working, which I think can be solved by using `deepcopy`  as I suggested.

2022-11-02 15:27 UTC, ajshajib commented on test/test_Plots/test_model_plot.py
> +        lensPlot.plot_main(with_caustics=True)
I suggest checking that `amp` keyword(s) within `kwargs_params` are staying the same as the initial.

2022-11-02 16:29 UTC, sibirrer commented on lenstronomy/Plots/model_plot.py
>          model, error_map, cov_param, param = self._imageModel.image_linear_solve(inv_bool=True, **kwargs_params)
ah, great catch! I made it slightly different such that the 'amp' parameters are updated if linear_solver=True but it's not happening if =False

2022-11-02 16:44 UTC, ajshajib approved these changes

2022-11-02 16:45 UTC, ajshajib commented
Great! Thanks for implementing the requested changes, feel free to merge with the main branch. 🙂

2022-11-02 16:46 UTC, merged