Addition of "EPL_boxydisky" lens profile and edit on relevant codes
lenstronomy/lenstronomy pull request #383
Opened 2022-11-01 22:36 UTC by Maverick-Oh

Hello, this is my 2nd pull request!

The main addition here is the addition of "epl_boxydisky.py" on "lenstronomy/LensModel/Profiles/". It is a purely boxy/disky profile added on EPL.

How it works
- It combines the standard "EPL" and "MULTIPOLE" profiles in a way that "MULTIPOLE" axis aligns with "EPL" axis, so that it's purely boxy/disky.
- Compared to the standard "EPL" profile, "EPL_boxydisky" has one more parameter, which is "a_m", the amplitude of the multipole with m=4 (octopole), which makes the surface mass density disky for a_m>0, boxy for a_m<0. The angle "phi" for "MULTIPOLE" is automatically calculated from "e1" and "e2" of "EPL".

Additional Comments
1. It is improvised to sync "EPL" angle and "MULTIPOLE" angle. "EPL" angle works with "e1" and "e2" parametrization, so that it is hard to joint it with "phi" angle parameterization of "MULTIPOLE" using lenstronomy's joint method.
2. This implementation is not so 'beautiful' in the sense that "EPL_boxydisky" defined like this would be just single-case improvision.
3. This implementation changes "solver4point.py", "lens_param.py", "profile_list_base" to make sure the new "EPL_boxydisky" works fine with normal routines, including mcmc.
4. The commit on Oct 24th has some irrelevant parts related to my previous pull request. I wanted to exclude this part but wasn't sure how I'm supposed to exclude. So I am just pull-requesting including them.

Thanks!

2022-11-01 23:07 UTC, sibirrer requested changes
Thanks a lot for the pull request! I fixed the merge conflicts and I have some design inputs in the comments.
You should also add test functions for this new model.
1. test that the differentials are matching each other. Can you add another definition as done for e.g. the 'EPL' model here: https://github.com/lenstronomy/lenstronomy/blob/1d9d46268e5dc3f72cb275fc12fca01d8908c5f3/test/test_LensModel/test_numeric_lens_differentials.py#L280
2. Write test function for the class. Make a new file and write at least one test function per routine that you wrote. You only need to test agains either other routines or for some conventions that you know the result. See e.g. https://github.com/lenstronomy/lenstronomy/blob/main/test/test_LensModel/test_Profiles/test_epl.py

Thanks a lot!
Beyond that, I will leave it to @dangilman to review
Simon

2022-11-01 23:07 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +class EPL_boxydisky(LensProfileBase):
in this class, you combine the EPL_major axis with the multipoles. This leads to some duplication of what is in the EPL model itself. Wouldn't it be better to have this class combining the EPL model and the Multipole one?

2022-11-01 23:07 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def function(self, x, y, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
the a_m parameter is not defined in the doc strings for most of the definitions

2022-11-02 02:12 UTC, dangilman requested changes
Hi Maverick, thank you for implementing this! I made some comments. My two main suggestions (in addition to those made by Simon, are 
1) I think you simplify this by creating an instance of EPL instead of EPLMajorAxis, and using the routines in EPL to compute lensing quantities. Then, you can use the multipole class to compute the lensing quantities for the multipole term, and then just add the outputs.  
2) it looks like a rotated multipole model is being added to an un-rotated epl model, you might want to check that this gives the correct behavior. I think this will result in the two profiles being misaligned by the angle phi_G.

2022-11-02 02:12 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        phi_m = phi_G
I suggest you write a function that returns the keyword arguments for the multipole model, since you'll need to compute these keyword arguments inside most of these routines. Basically, it would take as an input e1, e2, center_x, center_y, and a_m and return the dictionary of keyword arguments that you then pass to the multipole lens model class. To get the correct position angle for the multipole model from e1 and e2, you can use the "ellipticity2phi_q" function in Util.param_util.

2022-11-02 02:12 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.epl_major_axis = EPLMajorAxis()
I would just load the EPL model directly, and use those routines to compute the epl contribution to the derivatives, hessian, etc.

2022-11-02 18:54 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        b, t, q, phi_G = self.param_conv(theta_E, gamma, e1, e2)
That is true! I should have done it that way; originally I was looking into 'EPL' code and editing it to have MULTIPOLE. I'll change it that way.

2022-11-03 08:00 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        f__x_multipole, f__y_multipole = self.multipole.derivatives(x_, y_, self.m, a_m, phi_m)
x__ and y__ are rotated coordinates. It's fed into 'EPL_MAJOR_AXIS' to make a rotated EPL. It's basically how EPL is written.
x_ and y_ are unrotated coordinates. 'MULTIPOLE' makes it rotated with the given phi_m value.
I checked that those profiles are aligned together with varying e1 and e2 through a GUI I made using Jupyter notebook. Do you think I can share that Jupyter notebook too, to show that it works? If so, which directory should I share it to?

2022-11-03 08:01 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def function_epl_multipole_separately(self, x, y, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
Oh yes it was for testing... I'll delete it.

2022-11-10 21:25 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        f_xy = f_xy_epl = f_xy_multipole
this is probably a typo that will be picked up when you implement test functions. I highly recommend writing them before the actual implementation of the functions

2022-11-10 21:25 UTC, Maverick-Oh commented on lenstronomy/LensModel/Solver/solver4point.py
> +        elif lens_model == 'EPL_boxydisky':
Yes it is the same; I was dealing with some errors in MCMC processes. Now it's not necessary to be there separately, so I edited it.

2022-11-10 21:30 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        f_xy = f_xy_epl = f_xy_multipole
I see... I'll commit test functions soon. Can you specify which part the typo is, exactly?

2022-11-10 21:31 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.epl_major_axis = EPLMajorAxis()
Thanks for the comment. It's because I was learning how EPL is written and changing it to implement MULTIPOLE together. The newly committed version loads EPL model directly and makes use of it. Thanks!

2022-11-10 21:34 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +class EPL_boxydisky(LensProfileBase):
Yes it's from me having tried to learn the code structure while modifying EPL code. The newly committed version has removed such overlaps by loading EPL functionalities. Thanks!

2022-11-10 21:35 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    Elliptical Power Law mass profile
The newly committed version still does not have enough documentation compared to other files, I think. I'll add more to the following commits.

2022-11-10 21:37 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +__author__ = 'ntessore'
Yeah it's from copying EPL code first and editing it... I updated it to 'maverickoh'. Is there a convention how to write the author name? Should it be the same as my github name?

2022-11-10 21:38 UTC, Maverick-Oh commented on lenstronomy/LensModel/profile_list_base.py
> +        elif lens_type == 'EPL_boxydisky':
The newly committed version has capitalized everything. Thanks!

2022-11-14 23:22 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        f_xy = f_xy_epl = f_xy_multipole
you have an '=' sign instead of a '+' sign. This makes me surprised the tests are passing.

2022-11-14 23:23 UTC, sibirrer commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'theta_E': 2., 'e1': 0.1, 'e2': 0., 'gamma': 2.13, 'a_m': 0.1}
can you also test with 'e2' != 0? I am a bit surprised the tests are passing

2022-11-15 12:04 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        f_xy = f_xy_epl = f_xy_multipole
Oh now I see it... Yes I'm changing it.

2022-11-15 12:09 UTC, Maverick-Oh commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'theta_E': 2., 'e1': 0.1, 'e2': 0., 'gamma': 2.13, 'a_m': 0.1}
Yes! I'll try e2 != 0 too.
Another thing I wanted to try was making a meshgrid and check the derivatives. It didn't work as I thought so I changed it back.

For now, it's only checking along x axis:
x = np.linspace(start=0.1, stop=5.5, num=10)
y = np.zeros_like(x)
It can be great if we can check not only along x axis but all the first quadrant.

2022-11-15 12:14 UTC, Maverick-Oh commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'theta_E': 2., 'e1': 0.1, 'e2': 0., 'gamma': 2.13, 'a_m': 0.1}
With e2 = 0.2, it failed with the typo on the hessian.
With e2 = 0.2, it passed when the typo on the hessian is fixed.

2022-11-15 18:20 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +__author__ = 'ntessore'
github name is a good choice

2022-11-15 18:24 UTC, dangilman commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'theta_E': 2., 'e1': 0.1, 'e2': 0., 'gamma': 2.13, 'a_m': 0.1}
good, I also think it would be helpful to a write a test function for the lens profile, similar to the other tests executed in test_Profiles.

2022-11-18 03:32 UTC, dangilman requested changes
Hi Maverick, looks good. I just a made a few final stylistic comments, and have a question about the tests when center_x and center_y are non-zero (see my comments)

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.epl = EPL()
the last couple edits before merging have to do with private/public conventions in lenstronomy. Since self.epl will only be accessed in this class (i.e. nobody using the code will create an instance of EPL_BOXYDISKY and then access the .epl class created inside of it), it should be private with an underscore after the period, "self._epl"

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.multipole = Multipole()
make private self._multipole

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.m = int(4)
also private

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def set_static(self, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
I think this should call the set_static method in self._epl

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def set_dynamic(self):
same as comment above about set_static

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def derivatives(self, x, y, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
define a_m in the documentation

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        :param e2: eccentricity component
add a_m to docs

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        x_ = x - center_x
Do the tests pass if center_x and center_y are non zero? To be safe, I would not do the subtraction of x - center_x inside this class, and instead pass center_x and center_y into self._epl and self._multipole

2022-11-18 03:32 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        x_ = x - center_x
same comment regarding passing center_x/center_y into self._epl and self._multipole

2022-11-20 01:20 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def set_static(self, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
I have a concern about set_static methods. multipole.py does not have the functionality to set static and dynamic. For that reason, my epl_boxydisky.py's set_static and st_dynamic only set EPL part of the parameters static or dynamic. Do you think I should make some arrangements so that I can make Multipole to be static too?

2022-11-20 18:00 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def set_static(self, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
Actually, the set_static method would fix the orientation of the EPL profile, but without a similar routine added to the multipole model the orientation between the two profiles will be wrong. So I think you should just remove the set_static and set_dynamic methods for this class

2022-11-21 14:03 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def function(self, x, y, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
documentation for a_m added in each relevant function

2022-11-21 14:04 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +    def derivatives(self, x, y, theta_E, gamma, e1, e2, a_m, center_x=0, center_y=0):
documentation added

2022-11-21 14:22 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        :param e2: eccentricity component
documentation added

2022-11-21 14:24 UTC, Maverick-Oh commented on test/test_LensModel/test_numeric_lens_differentials.py
> +        kwargs = {'theta_E': 2., 'e1': 0.1, 'e2': 0., 'gamma': 2.13, 'a_m': 0.1}
test_Profiles/test_epl_boxydisky.py added

2022-11-21 14:24 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        self.epl = EPL()
self.epl -> self._epl
self.multipole -> self._multipole
self.m -> self._m
done!

2022-11-21 14:26 UTC, Maverick-Oh commented on lenstronomy/LensModel/Profiles/epl_boxydisky.py
> +        x_ = x - center_x
removing translation `x_ = x - x_center` and 
passing `center_x` and `center_y` done

2022-11-21 14:27 UTC, Maverick-Oh commented
I think every comment got resolved on my side. Please check and let me know what you think! Thanks.

2022-11-21 16:39 UTC, dangilman requested changes

2022-11-21 16:39 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_epl_boxydisky.py
> +a = TestEPL_BOXYDISKY()
looks good, just remove these lines in the test function and it should be good to go!

2022-11-21 16:56 UTC, dangilman commented on test/test_LensModel/test_Profiles/test_epl_boxydisky.py
> +a = TestEPL_BOXYDISKY()
ok it looks fine from my side @sibirrer

2022-11-21 17:09 UTC, sibirrer approved these changes
Looks good. Thank you @Maverick-Oh @dangilman

2022-11-21 17:10 UTC, merged