Improving zeus implementation
lenstronomy/lenstronomy pull request #385
Opened 2022-11-11 16:08 UTC by nataliehogg

I added the functionality to access three of the zeus callbacks, mainly useful for convergence diagnostics on running chains: https://zeus-mcmc.readthedocs.io/en/latest/api/callbacks.html.

I also moved all the zeus kwargs to be read from a dictionary that can be optionally passed as part of the fitting_kwargs_list to FittingSequence.

2022-11-11 17:39 UTC, sibirrer commented on lenstronomy/Workflow/fitting_sequence.py
> +                                                 shuffle_ensemble=zeus_settings.get('shuffle_ensemble', True), light_mode=zeus_settings.get('light_mode', False))
the .get() statement requires zeus_setting not to be None. This test fails. Can't you have **kwargs_zeus as the input of this definition?

2022-11-11 17:44 UTC, sibirrer requested changes
Thank you @nataliehogg !
The tests fail currently. You should avoid calling kwargs.get() in inputs of function calls. I made suggestions for keeping those all (or a portion of them) as keyword arguments passed as keyword arguments.

2022-11-11 17:44 UTC, sibirrer commented on lenstronomy/Sampling/sampler.py
>          sampler = zeus.EnsembleSampler(nwalkers=n_walkers, ndim=num_param, logprob_fn=self.chain.logL,
is it possible to have here a **kwargs_zeus statement of putting the arguments in here, to be flexible and the user knows that these arguments go directly into the Zeus code?

2022-11-11 17:44 UTC, sibirrer commented on lenstronomy/Sampling/sampler.py
> +                  autocorrelation_callback=False,
these arguments are not documented here. Perhaps keep them as kwargs_zeus and point towards the input in the actual Zeus function where they get called as **kwargs_zeus?

2022-11-14 14:07 UTC, nataliehogg commented on lenstronomy/Workflow/fitting_sequence.py
> +                                                 shuffle_ensemble=zeus_settings.get('shuffle_ensemble', True), light_mode=zeus_settings.get('light_mode', False))
This function now takes **kwargs_zeus

2022-11-14 14:10 UTC, nataliehogg commented
Hi @sibirrer I tried to modify things according to your suggestion. In particular, fitting sequence now only deals with **kwargs_zeus. However, I wanted to keep the kwargs_zeus.get() structure in mcmc_zeus in Sampler, because **kwargs_zeus cannot be passed to the individual callback functions of zeus (it will give an unexpected argument error). I didn't add the full documentation of all these kwargs; do you want me to?

The tests now pass locally for me.

2022-11-14 22:13 UTC, sibirrer requested changes
Thank you very much!
I have some minor suggested changes but I think other than that should be good.

2022-11-14 22:13 UTC, sibirrer commented on lenstronomy/Workflow/fitting_sequence.py
> +        :param zeus_settings: dictionary of zeus-specific kwargs
the naming is different here than the input. In this definition, since it's not exclusive to the zeus sampler, I would have the kwargs_zeus input statement not as '**' but as kwargs_zeus=None and then if kwargs_zeus=None: kwargs_zeus = {} or something like that

2022-11-14 22:13 UTC, sibirrer commented on test/test_Workflow/test_fitting_sequence.py
> +    def setup(self):
please change to setup_method as there were deprecation warnings

2022-11-14 22:13 UTC, sibirrer commented on lenstronomy/Sampling/sampler.py
> +        print(len(flat_samples))
remove

2022-11-14 22:13 UTC, sibirrer commented on lenstronomy/Sampling/sampler.py
>                                         blobs_dtype=blobs_dtype, verbose=verbose, check_walkers=check_walkers,
is it possible to have it organized that you can have a keyword argument in here that is flexible to changes of the Zeus API? Meaning that it is not needed to be hardcoded in lenstronomy what the arguments are? (at least for some of those). This might also be easier for testing of lenstronomy since I guess some options of the code above with if clauses were not tested

2022-11-15 11:12 UTC, nataliehogg commented on lenstronomy/Workflow/fitting_sequence.py
> +        :param zeus_settings: dictionary of zeus-specific kwargs
Docstring updated; kwargs_zeus is not a dictionary. I'm keeping it as **kwargs_zeus because that seems cleaner (if you would prefer it to be a separate dictionary I can change the rest of the implementation).

2022-11-15 11:16 UTC, nataliehogg commented on lenstronomy/Sampling/sampler.py
>                                         blobs_dtype=blobs_dtype, verbose=verbose, check_walkers=check_walkers,
I have changed this to **kwargs_zeus in the definition of mcmc_zeus as well. I will update the tests so that the if statements for the callbacks get checked as well.

2022-11-15 16:55 UTC, sibirrer approved these changes
Thank you @nataliehogg !
This looks good and things can always change in the future

2022-11-15 16:55 UTC, merged