added stretch_plot and shear_plot to lens_plot with tests
lenstronomy/lenstronomy pull request #396
Opened 2022-12-09 21:55 UTC by mattgomer

Two new plots for visualization of magnification and shear effects. 

stretch_plot plots a grid of ellipses stretched in accordance with the local Jacobian eigenvalues to show the direction and magnitude of stretch for an image in any given location. 
![image](https://user-images.githubusercontent.com/69860755/206801949-b287666c-03ae-4cb3-81f6-f119a5ad904d.png)

shear_plot plots a line segment corresponding in length to the magnitude of the shear (both internal and external) at each location. 
![image](https://user-images.githubusercontent.com/69860755/206802041-cc165b6c-3373-49f5-9fab-cd99b81da4ed.png)

2022-12-09 22:12 UTC, sibirrer requested changes
Looks great, thank you @mattgomer ! I left some minor formatting and style requests but otherwise ready to go/

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    :param kwargs: kwargs to send to matplotlib.pyplot.matshow()
aren't these kwargs going to add_patch()? Do you also want to have other kwargs going to patches.Ellipse()?

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +                       plot_grid= None, scale= 1, ellipse_color= 'k',
formatting: can you have the format in line with the arguments of the first line?

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +                       plot_grid= None, scale= 1, ellipse_color= 'k',
minor PEP8 formatting: no space in scale=1 arguments (and others) for input default arguments

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    stretch_1 = np.abs(1. / w1)  # stretch in direction of first eigenvalue (unsorted)
these stretches can go to infinity. Do you want to cap them to a certain size or not? (perhaps as an optional input argument?) Just a thought.

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +                       plot_grid= None, scale= 5, color= 'k',
same with formatting

2022-12-09 22:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    Plots shear (internal+external) pseudovectors at each point on a grid
can you give a bit more detailed information about this routine? Also, leave a space between the description and the parameter definitions

2022-12-09 22:12 UTC, sibirrer commented on test/test_Plots/test_lens_plot.py
> +    def test_shear_plot(self):
space between definitions

2022-12-12 22:23 UTC, mattgomer commented on lenstronomy/Plots/lens_plot.py
> +    stretch_1 = np.abs(1. / w1)  # stretch in direction of first eigenvalue (unsorted)
Good idea. Added a max_stretch argument that caps the stretches

2022-12-12 22:23 UTC, mattgomer commented on lenstronomy/Plots/lens_plot.py
> +    Plots shear (internal+external) pseudovectors at each point on a grid
Updated. Is this better?

2022-12-12 22:25 UTC, mattgomer commented on lenstronomy/Plots/lens_plot.py
> +                       plot_grid= None, scale= 1, ellipse_color= 'k',
I don't know of a way to have two mappable kwargs like **kwargs_patch and **kwargs_ax. I did play with it a bit and found that **kwargs_patch seems much more useful, so I changed it as such. Do you think a **kwargs_ax is necessary? If so, how can it be done?

2022-12-12 22:25 UTC, mattgomer commented on lenstronomy/Plots/lens_plot.py
> +    :param kwargs: kwargs to send to matplotlib.pyplot.matshow()
I don't know of a way to have two mappable kwargs like **kwargs_patch and **kwargs_ax. I did play with it a bit and found that **kwargs_patch seems much more useful, so I changed it as such. Do you think a **kwargs_ax is necessary? If so, how can it be done?

2022-12-12 22:51 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    :param kwargs: kwargs to send to matplotlib.pyplot.matshow()
It's ok for now. We add the feature when it's requested or being used. The idea was to have the function arguments as kwargs_blabla but without the '**' in this function call so it gets passed as a keyword argument instead as unpack as arguments. Then you can do several of them.

2022-12-12 22:51 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +                       plot_grid= None, scale= 1, ellipse_color= 'k',
almost, the idea is that when a new line starts that it starts at the same argument of the function call (meaning right under the '(' of the first line. It's ok and I adopt it.

2022-12-12 22:52 UTC, sibirrer approved these changes

2022-12-12 22:53 UTC, merged