fixed_lens_model keyword argument in likelihood evaluations
lenstronomy/lenstronomy pull request #407
Opened 2023-01-31 18:43 UTC by dangilman

Hi @sibirrer, this is a first go at adding a "fixed_lens_model" option when calling the likelihood function in FittingSequence. The changes are in the Param class and in the Image2SourceMapping class, where the new keyword argument stops lenstronomy from iterating through the array of lens model keyword arguments during each function call, and only ray traces to the source plane once during the first likelihood evaluation, respectively. This leads to about a factor of 2 improvement in speed when fitting source and lens light models to imaging data with a fixed lens model. I was, however, expecting more of an increase in speed

2023-01-31 19:09 UTC, sibirrer requested changes
Hi Daniel, thanks for the PR. I have some suggestions on the design, not sure they are all doable or not. About the speed difference: I would be curious to see a profiling run to see where the most computational time is spent for your problem and how much of it is the lensing calculation, and what is other things, before further improving a specific aspect.

2023-02-04 15:45 UTC, dangilman commented on lenstronomy/ImSim/image2source_mapping.py
> +    def _image2source_mapping(self, x, y, kwargs_lens):
yes I can implement something like this, although I thought the (x, y) coordinates when passed through the likelihood calls would always be the same when fitting imaging data since you're raytracing through a pre-determined set of pixels (unless I don't understand something).

2023-02-04 15:46 UTC, dangilman commented
Hi, I'll work on implementing your comments. I profiled the code and the most time is spent calling functions in the TNFW class, which means there are still ray shooting computations being performed somewhere. Do you know where that might be besides the image2source class?

2023-02-04 23:24 UTC, sibirrer commented
> Hi, I'll work on implementing your comments. I profiled the code and the most time is spent calling functions in the TNFW class, which means there are still ray shooting computations being performed somewhere. Do you know where that might be besides the image2source class?

Perhaps when calculating the positions of objects when defined in the image plane? Or solving the lens equation? I don't know all the options you are choosing but there are certainly some aspects that could require evaluations of the lens model prior to ray-tracing on the entire grid.

2023-02-04 23:25 UTC, sibirrer commented on lenstronomy/ImSim/image2source_mapping.py
> +    def _image2source_mapping(self, x, y, kwargs_lens):
It is most likely always the case in the current way how the code works, but the function as it is coded is not restricted to that case and hence could be broken moving forward.

2023-02-10 20:02 UTC, dangilman commented
Hi @sibirrer, I addressed some of your comments. I don't really understand the cause of the test failure in the latest pull request. It seems to crash only on the dynesty part of test_FittingSequence

2023-02-10 20:02 UTC, dangilman commented on lenstronomy/ImSim/image2source_mapping.py
> +    def _image2source_mapping(self, x, y, kwargs_lens):
@sibirrer I will implement your suggestion here in the next pull request

2023-02-10 20:03 UTC, dangilman commented on lenstronomy/Util/class_creator.py
> +                       fixed_lens_model=False):
done

2023-02-10 20:04 UTC, dangilman commented
> 

Yes, I tracked down all calls to ray-shooting and now the fixed_lens_model keyword argument will make sure they only happen once.

2023-02-11 03:30 UTC, sibirrer commented
> Hi @sibirrer, I addressed some of your comments. I don't really understand the cause of the test failure in the latest pull request. It seems to crash only on the dynesty part of test_FittingSequence

Hi @dangilman , there was a new dynesty release and apparently the test settings triggered an error message. I could fix it and merged the changes. If you pull the main branch, your test hopefully pass

2023-04-06 15:42 UTC, dangilman commented
@sibirrer I realized that the functionality I wanted when introducing the fixed_lens_model keyword argument could be achieved with the existing NumericalAlpha class in lenstronomy. The only change I needed to make was to add a keyword argument to kwargs_model that passes a user-defined deflection angle class to lenstronomy for sampling

2023-04-06 17:28 UTC, dangilman commented
> > @sibirrer I realized that the functionality I wanted when introducing the fixed_lens_model keyword argument could be achieved with the existing NumericalAlpha class in lenstronomy. The only change I needed to make was to add a keyword argument to kwargs_model that passes a user-defined deflection angle class to lenstronomy for sampling.
> > I also updated the name and documentation of the custom class to hopefully be more informative
> 
> Oh, that's great! Ping me once you want me to review the updated PR. Thanks a lot @dangilman !

I think it's ready, the test that failed doesn't seem to be related to the changes I made...

2023-04-06 17:36 UTC, sibirrer requested changes
Looks good! I have a few minor documentation requests and the tests fail in a file where yo made edits, so I expect the tests to pass before merging. Thank you!

2023-04-06 17:36 UTC, sibirrer commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +            g_shift = 0.005
does this have to do why the test is failing? Tests are failing in this file and there were done modifications.

2023-04-06 17:36 UTC, sibirrer commented on lenstronomy/LensModel/lens_param.py
> +        true if all lens components are fixed
can you add an additional space at the beginning of this line break (see format of other :param doc strings above). It makes a difference in the sphinx documentation.

2023-04-06 17:36 UTC, sibirrer commented on lenstronomy/PointSource/Types/base_ps.py
> +    def __init__(self, lens_model=None, fixed_magnification=False, additional_image=False, fixed_lens_model=False):
can you add a doc string for fixed_lens_model?

2023-04-06 17:36 UTC, sibirrer commented on lenstronomy/Util/class_creator.py
> +    :param fixed_lens_model: keeps the lens model fixed during likelihood calls; this setting should only be set to
can you also add a doc string for tabulated_deflection_angles?

2023-04-06 17:38 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/param_manager.py
> +            g_shift = 0.005
yep

2023-04-06 19:03 UTC, sibirrer approved these changes

2023-04-06 19:03 UTC, merged