PSF Fitting accounts for corners
lenstronomy/lenstronomy pull request #430
Opened 2023-03-27 04:34 UTC by amn3142

Lots of extra comments to try to help explain my thought process...
Test function right now only checks whether uniform kernels are returned as a final uniform kernel for a symmetry of 6.

2023-03-27 18:59 UTC, sibirrer requested changes
This looks good to me. I have some minor documentation format requests but otherwise ready to go. Thank you very much!

2023-03-27 18:59 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +         :boolean corner_symmetry: if the imposed symmetry is an odd number, the edges of the reconstructed PSF in its default form will be
follow the same documentation style with :param corner_symmetry:

2023-03-27 18:59 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +                supersampling_factor=point_source_supersampling_factor)
this is weird formatting. You might not need a line break here

2023-03-27 18:59 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +        keep_corners = type(corner_symmetry) == int
I don't understand this line. Isn't corner_symmetry supposed to be a boolean already?

2023-04-03 20:29 UTC, sibirrer commented
> Hi @sibirrer I realized it didn't make sense to calculate the corners mask potentially thousands of times, so I've moved the corner completeness calculation to before the iterative part of the psf fitting process. This changed some of the structure significantly, including adding a mask calculation function.
> 
> It all seems to work, however, I didn't think of a good way to actually use the test functions to check that the correct information is getting passed through update_iterative (other than on my own with print statements). I wanted to make sure this updated structure would be ok for you before I go through the other comments you had.

That sounds good @amn3142 ! For the test, you can simply check the individual function, no need for 'system-integrated' testing with dedicated outputs. Thanks a lot!

2023-04-03 23:04 UTC, amn3142 commented on lenstronomy/Workflow/psf_fitting.py
> +        ##TODO: Account for image edges/masked pixels.
This one is. Right now, we don't do any weighting based on missing information in the data (e.g. image edge or bad pixels).

2023-04-03 23:04 UTC, amn3142 commented on lenstronomy/Workflow/psf_fitting.py
> +        keep_corners = type(corner_symmetry) == int
typo... corner_symmetry should be an int or None, fixed.

2023-04-03 23:06 UTC, amn3142 commented
Ok I think I've now addressed all the comments hopefully, although there were a lot of formatting changes so hopefully didn't introduce too many new problems..

2023-04-04 01:26 UTC, sibirrer requested changes
Looks good. I have one larger request to add a test function for the calc_cornermask definition function and some minor pedantic things.
Thank you very much!

2023-04-04 01:26 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +         :boolean corner_symmetry: if the imposed symmetry is an odd number, the edges of the reconstructed PSF in its default form will be
:param corner_symmetry:

2023-04-04 01:26 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +        :param kwargs_psf: all the psf_kwargs, really only the kernel size is needed here
add space between description and the input definitions.

test ...

:param ....

2023-04-04 01:26 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +            kwargs_psf_new, logL_after, error_map = self.update_psf(kwargs_psf_new, kwargs_params, corner_mask,**kwargs_psf_update)
have a space between 'corner_mask, **kwargs_psf_update'

2023-04-04 01:26 UTC, sibirrer commented on test/test_Workflow/test_psf_fitting.py
add a separate test function for calc_cornermask() definition

2023-04-04 01:26 UTC, sibirrer commented on test/test_Workflow/test_psf_fitting.py
> -
add line. Two lines separation outside classes

2023-04-04 01:26 UTC, sibirrer commented on test/test_Workflow/test_psf_fitting.py
> -
add line. Two lines separation outside classes

2023-04-04 05:20 UTC, amn3142 commented
Ok hopefully this time I caught everything sorry I missed those formatting errors that you had already pointed out :(

2023-04-04 12:54 UTC, sibirrer approved these changes
This looks great. Thank you very much!

2023-04-04 12:54 UTC, merged