Fix the model plot linear solver for interferometric likelihood method
lenstronomy/lenstronomy pull request #432
Opened 2023-03-28 22:40 UTC by nanz6

Fix the model plot linear solver for interferometric likelihood method.

In the SingleBandMultiModel.image_linear_solve, the wls_model should be the convolved model image, where the returned wls_model from the interferometric _image_linear_solve is [unconvolved, convolved] images. Here wls_model just needs to be assigned to get the second array of _image_linear_solve model output. By doing this, no errors would be raised.

Add a part in test_model_plot to ensure that the error will NOT be raised for the interferometry model plot linear solver, using a try, except, else structure.

2023-03-28 22:53 UTC, sibirrer requested changes
Sounds great, and glad it did not take much to make it happen. I am not sure the test functions are properly made. I don't expect you to have a raise test for this part as it should run through.

2023-03-28 22:53 UTC, sibirrer commented on test/test_Plots/test_model_plot.py
> +                kwargs_data = sim_util.data_configure_simple(numPix=10, deltaPix=1, background_rms=1, exposure_time=1)
I don't really understand this test here. Do you expect this function to raise? The test function is expecting a VaueError raise, but then you have a try/except with an else statement that by definition gives you a ValueError.

2023-03-28 22:58 UTC, nanz6 commented on test/test_Plots/test_model_plot.py
> +                kwargs_data = sim_util.data_configure_simple(numPix=10, deltaPix=1, background_rms=1, exposure_time=1)
I don't like this part neither, so I can remove it.

The idea is to check the part executed by try will not raise errors. 
If the try part raises errors, then it would excute the "except: pass", which will not finally raise an error, then assertRaises will report that the test is not passed.
If the try part does not raise errors, it would raise error in the "else: raise..." part, which would pass the assertRaises test.

2023-03-28 23:01 UTC, sibirrer commented on test/test_Plots/test_model_plot.py
> +                kwargs_data = sim_util.data_configure_simple(numPix=10, deltaPix=1, background_rms=1, exposure_time=1)
could you simply remove the raiseTest and have this part of the test in a regular test_ function? Would be nice checking that it works with the interferometric data, such that further changes do consider this case

2023-03-29 00:55 UTC, sibirrer approved these changes
Excellent! Thank you very much!

2023-03-29 00:55 UTC, merged