Enforce parameter limits in SpecialParam class
lenstronomy/lenstronomy pull request #464
Opened 2023-05-01 22:28 UTC by ajshajib

This PR:
- reverts enforcing initial parameter limits within the `FittingSequence` class, since it is already being done by the `ParticleSwarmOptimizer` class.
- directly imposes the user-defined bound through `SpecialParam.get_params()` to avoid error thrown when a lens-plane redshift is sampled higher than the reference source-plane redshift in the multi-plane mode, as parameters outside the user-defined bounds can be sampled by `ParticleSwarmOptimizer`.

2023-05-01 22:45 UTC, sibirrer requested changes
I see that you want to assure that all the kwargs_special (in particular the redshifts) are always in the bounds. The changes, it looks to me, would change it for all the other parameters since the initial guess in the ball of particles would not behave this way.

2023-05-01 22:45 UTC, sibirrer commented on lenstronomy/Workflow/fitting_sequence.py
> -        lower_limit, upper_limit = param_class.param_limits()
I am not sure this change does the same. I understand that the kwargs_special parameters get within the bounds, but for all the rest this initial ball of parameters could still be out of bounds

2023-05-01 22:48 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> -        lower_limit, upper_limit = param_class.param_limits()
These limits are already being set by `Sampler.pso()`, so I removed these lines to avoid redundancy.

2023-05-01 23:52 UTC, sibirrer commented on lenstronomy/Workflow/fitting_sequence.py
> -        lower_limit, upper_limit = param_class.param_limits()
Ah, I see. Thanks

2023-05-02 00:36 UTC, sibirrer commented
I see. So if you add a test that runs through all the new lines, that would be great. And then we are set to merge

2023-05-02 02:17 UTC, sibirrer approved these changes
Looks good. Thank you!

2023-05-02 02:17 UTC, merged