Coolest interface
lenstronomy/lenstronomy pull request #465
Opened 2023-05-03 14:31 UTC by LyneVdV

#452 
interface with the `COOLEST` templates for lenstronomy

NB: need to install COOLEST from https://github.com/aymgal/COOLEST.git and jsonpickle if not already there

2023-05-10 02:48 UTC, ajshajib commented
@LyneVdV Can you kindly add `COOLEST` in the `test_requirements.txt` and have the tests passed?

2023-05-10 02:49 UTC, ajshajib commented on lenstronomy/Util/coolest_interface.py
> +def create_lenstro_from_coolest(file_name):
```suggestion
def create_lenstronomy_from_coolest(file_name):
```

2023-05-10 02:52 UTC, ajshajib commented on lenstronomy/Util/coolest_interface.py
> +    Input
@sibirrer, will this Numpydoc-style docstring cause an issue with the documentation auto-generation?

2023-05-10 02:54 UTC, ajshajib commented on lenstronomy/Util/coolest_interface.py
> +def update_coolest_from_lenstro(file_name, kwargs_result, kwargs_mcmc=None,
```suggestion
def update_coolest_from_lenstronomy(file_name, kwargs_result, kwargs_mcmc=None,
```

2023-05-10 02:55 UTC, ajshajib commented on lenstronomy/Util/coolest_read_util.py
> +def shapelet_amp_COOLEST2lenstro(value):
```suggestion
def shapelet_amp_coolest_to_lenstronomy(value):
```

2023-05-10 13:01 UTC, LyneVdV commented
> > @LyneVdV Can you kindly add `COOLEST` in the `test_requirements.txt` and have the tests passed?
> 
> @ajshajib I have trouble with importing coolest from github with the test_requirements.txt. Have you ever done it ? I will continue searching for a solution

To my understanding, the line "coolest @ git+https://github.com/aymgal/COOLEST.git" in test_requirements makes a `pip install 'coolest @ git+https://github.com/aymgal/COOLEST.git'` run when the packages are installed for the tests. Locally I tried those line of codes and I think I understand better the problem. Doing  `pip install 'coolest @ git+https://github.com/aymgal/COOLEST.git'`  does create a coolest folder but there is only __pycache__ folder and __init__.py file inside, the package in itself is not downloaded... @aymgal do you have any insight on this ?

2023-05-10 13:11 UTC, aymgal commented
@LyneVdV would `git+https://github.com/aymgal/coolest@main#egg=coolest` work instead?

2023-05-11 08:14 UTC, LyneVdV commented
> @LyneVdV would `git+https://github.com/aymgal/coolest@main#egg=coolest` work instead?

No :/

2023-05-11 11:37 UTC, LyneVdV commented
> > @LyneVdV would `git+https://github.com/aymgal/coolest@main#egg=coolest` work instead?
> 
> No :/

@aymgal thank you for solving this import issue which was arising from the setup.py content in coolest

2023-05-11 15:28 UTC, LyneVdV commented
@ajshajib @sibirrer the issues for importing coolest seems to be all fixed now. However, in the test_interface, a PEMD model is used, which seems to require fastell4py. I tried adding it into the requirements but the import fails. I guess you already encountered similar issues at some point ? Do you have any advice on how to import fastell4py correctly ?

2023-05-11 15:31 UTC, LyneVdV commented on test_requirements.txt
> +git+https://github.com/sibirrer/fastell4py@master#egg=fastell4py
The example coolest template is with PEMD model hence pulling the PEMD model from lenstronomy but I can modify the test to have it use a SIE instead !

2023-05-12 08:56 UTC, LyneVdV commented
@ajshajib Do you need anything else from my side :) ?

2023-05-12 19:33 UTC, sibirrer commented
> @sibirrer, there is a difference of -0.6% in the coverage. I tried to see what kind of lines they are on the Coveralls website, but they are not showing up. Is there an alternate way to check the missed lines?

you can execute it locally with $make coverage 

or (from makefile)
coverage:
	coverage run --source lenstronomy setup.py test
	coverage report -m
	coverage html
	open htmlcov/index.html

2023-05-13 01:43 UTC, ajshajib requested changes
Thanks a lot for your hard work! This is a very extensive PR. I left many suggestions, which you can directly incorporate by clicking the provided button on GitHub. Some of them are for changing variable names to comply with PEP8 (in fact, most suggestions are for PEP8 or to improve the readability of code). You may also need to refactor the variable and function names in other places they are used. If you are using an IDE like PyCharm, that should be quick.

Also, please check the coverage report as @sibirrer suggested above and cover the missing lines in the test. We strive to have all newly added lines of code covered. Usually, these are unvisited lines within `if else` statements. In that case, it should be rather easy to cover them.

2023-05-13 01:43 UTC, ajshajib commented on test/test_Util/test_coolest.py
> +        return
```suggestion
        return
        
```

2023-05-15 08:14 UTC, LyneVdV commented on lenstronomy/Util/coolest_read_util.py
> +        gamma1 = gamma_ext * np.cos(2 * angle)
Unfortunately, there is a specific reason: the angles in COOLEST are taken from North towards East while lenstronomy will have angles from x towards y (ie from East towards North)

2023-05-15 08:23 UTC, LyneVdV commented on lenstronomy/Util/coolest_read_util.py
> +        print('cleaning true')
Yes it is ! Thanks !

2023-05-15 09:35 UTC, LyneVdV commented on lenstronomy/Util/coolest_interface.py
> +                            print('Lens Light : ')
yes as above for lens mass and shear

2023-05-15 09:35 UTC, LyneVdV commented on lenstronomy/Util/coolest_interface.py
> +                            print('Source Light : ')
yes ! As for shear, lens mass, lens light

2023-05-15 10:37 UTC, LyneVdV commented on lenstronomy/Util/coolest_interface.py
> +                    galac = lensing_entity
galac refers to any galaxy (lens or source). Renamed` galaxy` .

2023-05-15 11:06 UTC, LyneVdV commented on lenstronomy/Util/coolest_read_util.py
> +        gamma1 = gamma_ext * np.cos(2 * angle)
But once the angle is computed, lenstronomy functions can be used for the remaining transformations.

2023-05-15 15:19 UTC, LyneVdV commented
> Thanks a lot for your hard work! This is a very extensive PR. I left many suggestions, which you can directly incorporate by clicking the provided button on GitHub. Some of them are for changing variable names to comply with PEP8 (in fact, most suggestions are for PEP8 or to improve the readability of code). You may also need to refactor the variable and function names in other places they are used. If you are using an IDE like PyCharm, that should be quick.
> 
> Also, please check the coverage report as @sibirrer suggested above and cover the missing lines in the test. We strive to have all newly added lines of code covered. Usually, these are unvisited lines within `if else` statements. In that case, it should be rather easy to cover them.

I update the code according to the suggestions. I will work on the coverage !

2023-05-16 20:15 UTC, ajshajib commented
@LyneVdV, thanks a lot for your arduous work. This looks great from my side!

2023-05-16 20:15 UTC, ajshajib approved these changes

2023-05-16 21:31 UTC, sibirrer requested changes
Thanks a lot @LyneVdV  @ajshajib !
I have a few minor requests on documenting input and outputs in some definitions.
It's ok for now to leave the ones you have in numpy-style. For those that do not follow a convention, can you please add them in the current lenstronomy style with :param <variable name>: ...

Thank you very much!

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_interface.py
> +    Input
probably it will, but can also be fixed afterwards. We currently don't have a CI for documentation testing and hence I cleaned up some documentation afterwards.

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_interface.py
> +    Side fuction to create the minimum, maximum and whole redshift list of galaxies in the COOLEST template
can input and output be documented?

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_read_util.py
> +    to lenstronomy conventions (x following ra, to the left)
can you document input 'value'

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_read_util.py
> +    into an angle in radian in lenstronomy conventions (from x to y with x pointing to the left - aka North of East)
can you document input 'value'

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_read_util.py
> +    Transform q and phi (axis ratio, position angle East-of-North) to e1,e2 in lenstronomy
```suggestion
    Transform q and phi (axis ratio, position angle East-of-North) to e1,e2 in lenstronomy
   
     :param q: axis ratio
     :param phi: position angle East-of-North
     ```

2023-05-16 21:31 UTC, sibirrer commented on lenstronomy/Util/coolest_read_util.py
> +    Transform gamma_ext and phi_ext (shear strength, position angle East-of-North)
dito about doc strings format with :param <input variable>: ....

2023-05-17 09:31 UTC, LyneVdV commented
> Thanks a lot @LyneVdV @ajshajib ! I have a few minor requests on documenting input and outputs in some definitions. It's ok for now to leave the ones you have in numpy-style. For those that do not follow a convention, can you please add them in the current lenstronomy style with :param : ...
> 
> Thank you very much!

Hi @sibirrer  !
I updated the docstrings in lenstronomy style, adding relevant parameters description when needed :) !

2023-05-17 11:39 UTC, sibirrer approved these changes
thanks a lot @LyneVdV !
all good to merge!

2023-05-17 11:40 UTC, merged