Change sampler naming conventions
lenstronomy/lenstronomy pull request #479
Opened 2023-06-20 10:26 UTC by nataliehogg

This PR resolves #477 by renaming the various samplers available in lenstronomy so that the software names are used instead of a mixture of software names and sampling algorithms (as also discussed in #475). The software names are typeset according to the format chosen by the authors of the original packages.

Backwards compatibility is maintained with the 'MCMC' keyword argument defaulting to emcee. Backwards compatibility with 'nested_sampling' is not maintained; anyone using this option will now have to select 'dynesty', 'dyPolyChord' or 'MultiNest'. The sampler_type keyword argument in mcmc() and nested_sampling() is deprecated; if a user passes this keyword argument, a warning is printed and the option ignored.

2023-06-25 03:35 UTC, ajshajib requested changes

2023-06-25 03:35 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +            self.fitting_type = fitting[0]
I think keeping the `sampler_type` variable to pass the sampler name to the corresponding function(s) instead of `self.fitting_type` may be a more explicit way to do it. The sampling functions are intended to be public, but if they depend on `self.fitting_type`, which may cause issues for a future user/extension as this is not documented. The fix would be to set `self.fitting_type` before calling the function, but sticking with a direct argument for `sampler_type` for MCMC routines would keep things straightforward. But am I missing some other issue if the argument is passed directly?

2023-07-04 10:26 UTC, nataliehogg commented on lenstronomy/Workflow/fitting_sequence.py
> +            self.fitting_type = fitting[0]
My goal was to make it so that the functions of `fitting_type` and `sampler_type` are merged into one. This would mean that the user would not need to specify e.g. both 'nested_sampling' and 'dynesty' in the list that's passed to FittingSequence(), but rather just the software name. But if the two should remain separate I can revert those changes. I'm not sure I understand your suggestion just yet -- I'll play around with it.

2023-07-04 13:19 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
>               **kwargs_zeus):
```suggestion
    def mcmc(self,
             n_burn, n_run, walkerRatio=None, n_walkers=None, sigma_scale=1, threadCount=1, init_samples=None, re_use_samples=True,
             sampler_type='EMCEE',
             progress=True, backend_filename=None, start_from_backend=False,
             **kwargs_zeus):
```

2023-07-04 13:19 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
>                  elif kwargs['init_samples'] is None:
Below here, I suggest to pass `sampler_type` explicitly to `mcmc()` as:

```
mcmc_output = self.mcmc(**kwargs, sampler_type=fitting_type)
```

2023-07-04 13:19 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +        if self.fitting_type == 'zeus':
```suggestion
        if sampler_type == 'zeus':
```

2023-07-04 13:19 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +            output = [self.fitting_type, samples, param_list, dist]
```suggestion
            output = [sampler_type, samples, param_list, dist]
```

2023-07-04 13:19 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +            output = [self.fitting_type, samples, param_list, dist]
```suggestion
            output = [sampler_type, samples, param_list, dist]
```

2023-07-04 13:26 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +            self.fitting_type = fitting[0]
I think `sampler_type` does not need to be specified by the user, but this variable can still be used internally to pass the sampler type to the associated methods. In that way, `mcmc()` and `nested_sampling()` can still be used as a "public" method by a user without having to explicitly set `self.fitting_type` before calling them (here I am thinking about a general use case where a user may be using the public methods directly for any purpose outside the usual use case of calling `FittingSequence.fit_sequence()`). I have left some direct code suggestions for the example case of `mcmc()` for how I mean this to be implemented, but similar usage of the `sampler_type` variable also applies to `nested_sampling()` method. But please let me know if something is still unclear. 🙂

2023-11-23 06:36 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +                # == 'MCMC' or fitting_type == 'emcee' or fitting_type == 'zeus'):
```suggestion
```

2023-11-23 06:37 UTC, ajshajib commented on lenstronomy/Workflow/fitting_sequence.py
> +            ):
```suggestion
            elif fitting_type in ["dynesty", "dyPolyChord", "MultiNest"]:
```

2023-11-23 08:42 UTC, ajshajib approved these changes

2023-11-23 08:45 UTC, ajshajib commented
Thanks for the PR, @nataliehogg! I went ahead and resolved the conversations with new commits. 

@sibirrer, I approved the PR. Please feel free to merge when appropriate. This PR changes the expected `"fitting_type"` keywords for the sampling, so it won't be backward compatible for some cases.

2023-11-23 09:22 UTC, nataliehogg commented
thank you @ajshajib !

2023-11-23 14:42 UTC, merged

2023-11-23 14:43 UTC, sibirrer commented
Thank you very much @nataliehogg @ajshajib ! This is a great improvement and adds clarity to the samplers and design