Add substructure plot
lenstronomy/lenstronomy pull request #485
Opened 2023-07-12 18:44 UTC by dangilman

I made a new routine in model_band_plot that plots the effective multiplane convergence in substructure. I also made some minor fixes to other classes, including adding the "observed_convention_index" option to model API and removing a redundant line of code

2023-07-12 20:47 UTC, sibirrer requested changes
Looks good to me. I have some very minor requests and a question about two removed lines of code. Thanks a lot!

2023-07-12 20:47 UTC, sibirrer commented on lenstronomy/Plots/model_band_plot.py
> +        :param ax: matplotib axis instance
can you add a empty line here. For some reasons, readthedocs otherwise messes up the html

2023-07-12 20:47 UTC, sibirrer commented on lenstronomy/Plots/plot_util.py
> -
conventions for definitions outside of classes is two empty lines

2023-07-12 20:47 UTC, sibirrer commented on lenstronomy/SimulationAPI/model_api.py
> +        Effectively a fixed lens model. See documentation in Profiles.numerical_alpha
sphinx messes up when you do not include one whitespace in new lines with the same parameter

2023-07-12 20:47 UTC, sibirrer commented on lenstronomy/SimulationAPI/model_api.py
> +        values correspond to the observed (lensed positions), not the physical positions in space
single whitespace to be added

2023-07-12 20:47 UTC, sibirrer commented on lenstronomy/Workflow/update_manager.py
> -        if 'fixed_lens_model' in self.kwargs_constraints.keys():
is there a reason to remove these lines? It might break someones application

2023-07-12 20:52 UTC, dangilman commented on lenstronomy/Workflow/update_manager.py
> -        if 'fixed_lens_model' in self.kwargs_constraints.keys():
I added 'fixed_lens_model' as part of an older pull request, but then realized I could get the same functionality another way. I then went back and deleted all "fixed_lens_model" keyword arguments from functions/classes, but apparently missed this one

2023-07-12 21:11 UTC, sibirrer commented on lenstronomy/Workflow/update_manager.py
> -        if 'fixed_lens_model' in self.kwargs_constraints.keys():
thanks for the clarification

2023-07-12 21:12 UTC, sibirrer commented
@dangilman there seems to be an added line that is missed in the tests. I don't really know which one, or perhaps it is because of deleted lines?

2023-07-13 15:33 UTC, dangilman commented
> @dangilman there seems to be an added line that is missed in the tests. I don't really know which one, or perhaps it is because of deleted lines?

I think it was because of an if/else statement that checks for a multiplane lens model. I added a multiplane lens model to the tests which should hit the line

2023-07-13 15:47 UTC, sibirrer commented
Thank you @dangilman!

2023-07-13 15:47 UTC, merged