Stellar Kinematics Neural Network (SKiNN)
lenstronomy/lenstronomy pull request #489
Opened 2023-07-20 14:57 UTC by mattgomer

This update adds functionality through the SKiNN package, which emulates JAM via a neural network,  to perform joint lensing+dynamical modeling. This adds a kinematic_2D_likelihood term which can be sampled when "kinematic_2D_likelihood=True" in the likelihood. We have also added a data class to implement binned 2D kinematic data. 

SKiNN is limited to PEMD mass profiles and Sersic light profiles, and samples using q and phi, for which we have created the PEMD_Q_PHI profile and SERSIC_ELLIPSE_Q_PHI profile. The limitation to a PEMD leads to an issue when testing on github due to the fastell4py fortran compiler issue. We should discuss our options here, since SKiNN only works with a PEMD profile. Perhaps we can amend it to also work with an SIE for testing purposes?

2023-07-20 15:15 UTC, sibirrer commented
Thanks for the PR @mattgomer! 
For the PEMD model, you could replace it with the EPL model, which is basically the same, but does not need fastell4py (I more recently tend to use the EPL model but left the PEMD the same way for prosperity).
Regarding the (phi, q) vs (e1, e2) parameterization: My experience is that the fitting in (e1, e2) space is easier. Isn't it possible to translate the (e1, e2) parameters into (phi, q) at the level of the kinematic likelihood instead of the lens model? Or was there a particular reason why you want to sample in q, phi space?

In the meantime I left some minor comments and will review things in more detail later.

2023-07-20 15:23 UTC, mattgomer commented
> Thanks for the PR @mattgomer! For the PEMD model, you could replace it with the EPL model, which is basically the same, but does not need fastell4py (I more recently tend to use the EPL model but left the PEMD the same way for prosperity). 

Cool! Does the EPL return the exact same as the PEMD, or could it lead to differences if I replace the PEMD with the EPL? (And if so, how big are these differences? Maybe it would be okay) The NN was trained with GLEE's implementation of the PEMD anyway, and we use Sebastian's code to convert between GLEE and lenstronomy conventions, so maybe it's not critical in the end which lenstronomy implementation is used, as long as it maps back to the correct GLEE parameters.

>Regarding the (phi, q) vs (e1, e2) parameterization: My experience is that the fitting in (e1, e2) space is easier. Isn't it possible to translate the (e1, e2) parameters into (phi, q) at the level of the kinematic likelihood instead of the lens model? Or was there a particular reason why you want to sample in q, phi space?

If I recall correctly, the reason was that the NN call requires the input to be in q ,phi and we didn't want to reinitialize a lenstronomy model at each call of the NN to convert from e1,e2, to q,phi. But as I'm thinking about it, I'm not sure this is necessary because we may be able to simply convert during the step where the NN is called without needing a lenstronomy model. We were worried about this conversion slowing down the call, but if we don't need to reinitialize a model I think the time sink will be essentially zero.

2023-07-20 15:28 UTC, sibirrer commented
> Cool! Does the EPL return the exact same as the PEMD, or could it lead to differences if I replace the PEMD with the EPL? (And if so, how big are these differences? Maybe it would be okay) The NN was trained with GLEE's implementation of the PEMD anyway, and we use Sebastian's code to convert between GLEE and lenstronomy conventions, so maybe it's not critical in the end which lenstronomy implementation is used, as long as it maps back to the correct GLEE parameters.

It gives the same result. I tested it with this test function: https://github.com/lenstronomy/lenstronomy/blob/977412209625b3508d08fed6241304e0d03582db/test/test_LensModel/test_Profiles/test_epl.py#L155

2023-07-20 15:30 UTC, sibirrer commented
> > Regarding the (phi, q) vs (e1, e2) parameterization: My experience is that the fitting in (e1, e2) space is easier. Isn't it possible to translate the (e1, e2) parameters into (phi, q) at the level of the kinematic likelihood instead of the lens model? Or was there a particular reason why you want to sample in q, phi space?
> 
> If I recall correctly, the reason was that the NN call requires the input to be in q ,phi and we didn't want to reinitialize a lenstronomy model at each call of the NN to convert from e1,e2, to q,phi. But as I'm thinking about it, I'm not sure this is necessary because we may be able to simply convert during the step where the NN is called without needing a lenstronomy model. We were worried about this conversion slowing down the call, but if we don't need to reinitialize a model I think the time sink will be essentially zero.

Yeah, maybe think about 'just' converting the (e1, e2) space before putting it into the NN likelihood. If this leads to overall better behavior, no need to go the longer route of having another set of definitions for lens models. There might in the longer run also a more generalizable way to switch between (q, phi) and (e1, e2) in the sampling, as many models are in that regard self-similar

2023-07-20 15:31 UTC, sibirrer requested changes
ok, here some first minor comments. The tests are failing and let's focus first on the higher level discussion.

Please ping me again when you would like a more detailed review. Thank you!

2023-07-20 15:31 UTC, sibirrer commented on lenstronomy/LightModel/linear_basis.py
> +                elif model in ['SHAPELETS', 'SHAPELETS_POLsAR', 'SHAPELETS_POLAR_EXP',
I guess this is a typo

2023-07-20 15:31 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/kinematic_2D_likelihood.py
> +        log_like = (vrms - self.data)**2 / self.noise**2
this likelihood assumes uncorrelated noise properties, while in reality a lot of the systematics might be correlated between the data elements

2023-07-20 15:31 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/kinematic_NN_call.py
> +                  Get SKiNN from https://github.com/lucabig/lensing_odyssey_kinematics")
it looks like this package is not public (yet) or is the link wrong?

2023-07-20 15:31 UTC, sibirrer commented on lenstronomy/Sampling/likelihood.py
> +        self._kwargs_imaging = {'multi_band_list': multi_band_list, 'multi_band_type': multi_band_type,
you set this object to private. I am not sure this breaks some backwards compatibilities with other routines that would like to access this dictionary outside of the class

2023-07-20 15:31 UTC, sibirrer commented on lenstronomy/Data/kinematic_bin_2D.py
> +    def KinBin2kwargs(self):
can you make sure you follow the standard of leaving one blank line between definitions and definitions are lower case, such as kin_bin2kwargs(). Caps is for classes according to PEP8

2023-07-21 15:45 UTC, mattgomer commented on lenstronomy/Sampling/likelihood.py
> +        self._kwargs_imaging = {'multi_band_list': multi_band_list, 'multi_band_type': multi_band_type,
I changed  `self._kwargs_imaging` to `self.kwargs_imaging`, although note that this is inconsistent with the notation of `self._kwargs_time_delay` and `self._kwargs_flux`. Is there another routine somewhere that calls `LikelihoodModule.kwargs_imaging` instead of `LikelihoodModule._kwargs_imaging`? Is that the problem?

2023-07-21 18:36 UTC, mattgomer commented
@sibirrer Halfway through implementing these changes, I rediscovered why we used the Q_PHI profiles. SKiNN was trained with the q of the mass and light allowed to vary but the PAs are aligned. So if you wanted to fix that in lenstronomy it's hard because you can't fix e1 and e2 to allow the same phi. Instead we made these profiles so we can fix phi and sample q. I have an alternative, but I don't think it's better:

We could sample with e1 and e2, but make a check when the NN is called to confirm that the PAs are the same between mass and light. One problem with this is for small e the PA is ill-defined, so we might actually want to check if q is close to 1 OR the PAs are close. The bigger problem is that this would waste time sampling, because the e2 doesn't "know" that it should be close to e1 (for example) to get the right PA, so a penalty would waste every sample where they don't lie close together. This could get especially difficult if q goes close to 1, the e1 and e2 become uncoupled, and then q increases again with e1 and e2 totally uncorrelated, therefore having to waste time sampling to get them lined up again.

So I could make an EPL_Q_PHI class  and the current SERSIC_ELLIPSE_Q_PHI and sample with q and phi, or we can throw out a large fraction of samples. What do you think?

2023-07-21 18:46 UTC, sibirrer commented
> 
> So I could make an EPL_Q_PHI class and the current SERSIC_ELLIPSE_Q_PHI and sample with q and phi, or we can throw out a large fraction of samples. What do you think?


I see @mattgomer, then it's probably better to have a EPL_Q_PHI model. I am thinking of how to generalize such that in principle all models currently parameterized with (e1, e2) may also have an option to sample from (q, phi). This might take a while but could potentially save having new code. Potentially this could work with inheritance of a class that just takes q, phi and then calls the previous function with e1,e2 arguments transformed from the input. But that can be down the road

2023-07-22 16:45 UTC, mattgomer commented on lenstronomy/Sampling/Likelihoods/kinematic_2D_likelihood.py
> +        log_like = (vrms - self.data)**2 / self.noise**2
Now uses the correlation matrix

2023-07-22 16:49 UTC, mattgomer commented
@sibirrer  I've made these updates and the tests look like they're passing now. Note that the tests are under statements like 
```
self.kinematic_NN = kinematic_NN_call.kinematic_NN().SKiNN_installed
if self.kinematic_NN:
        ...
```

so they don't run if the NN is not installed, which is what happens on github. Locally, they run fine with the NN installed.

2023-07-24 14:24 UTC, sibirrer requested changes
Thank you @mattgomer !
I left quite some comments, many of them for PEP8 standards. I have not marked all of them (and did not find all for sure). I would recommend adding a plugin to check for those on your editor. There are many either missing empty lines, spacing off between operations, naming conventions off.

Then I am not sure about the alignment between HST and kinematics and what this is about. There should not be needed an alignment since the coordinate system is universally chosen. Maybe it is between the neural network training and the actual data cube, then fine, but it should be specified as such.

Another comment is that many of the NN training parts are very hard coded and not obvious to the user. I'd suggest adding a separate training configuration file that then can be linked in the actual likelihood module to cleanly separate the training from the evaluation of the likelihood, as well as the definition of the data.
The goal should be that someone else could also re-train with a different training set and still be able to use this code.

Then the test coverage has quite a bit decreased, despite moving to the EPL and adding your package to the test requirements. Unfortunately, the exact lines are not shown on the coverage report but you can also run it locally with 'make coverage' (have a look at the make file).

Thank you very much!

2023-07-24 14:24 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/kinematic_NN_call.py
> +                print('NN CALL WARNING: R_sersic is not within theta_E training bounds!')
this print statement is a bit confusing

2023-07-24 14:24 UTC, sibirrer commented on lenstronomy/Sampling/likelihood.py
> +            if kwargs_model['lens_light_model_list'][kin_lens_light_idx] not in ['SERSIC_ELLIPSE_Q_PHI']:
is this still required or can you use the default SERSIC_ELLIPSE model and then convert e1, e2 into phi, q?

2023-07-24 14:24 UTC, sibirrer commented on lenstronomy/Util/image_util.py
> +    querries scipy.ndimage.shift routine
check the documentation by typing 'make docs'. Empty line should be between description and parameter definitions

2023-07-24 14:24 UTC, sibirrer commented on lenstronomy/Util/kin_sampling_util.py
> +    def rotateHST_into_kinNN(self, HST_x, HST_y, ellipse_PA_to_hstx_angle,
I am not sure why this is needed. All the individual data can have completely different alignments and coordinate zero points and no particular parameterization is aligned with the HST or any other imaging data

2023-07-24 14:24 UTC, sibirrer commented on test/test_LensModel/test_Profiles/test_epl.py
> +    class TestEPLvsEPL_QPHI(object):
can you add the EPL_Q_PHI model to do the numerical differential testings? There is a separate test file and you can add a simple definition, just to check whether the differentials match between potential, deflection, and hessian

2023-07-24 14:24 UTC, sibirrer commented on test/test_Sampling/test_Likelihoods/test_kinematic_2D_likelihood.py
> +            #test  that doubling variance decreases logL by factor of 2
can you also test that when you put the parameters 1-sigma off, you get a 1-sigma likelihood difference?

2023-07-24 14:24 UTC, sibirrer commented on test/test_Util/coolest_template_update_pyAPI.json
> +                    "value": 0.014766053302355864
why have these parameters changed?

2023-07-31 17:11 UTC, mattgomer commented on lenstronomy/Data/kinematic_bin_2D.py
> +        if transform_pix2angle is None:
removed possibility to have no transform_pix2angle. Is that what you mean?

2023-07-31 17:12 UTC, mattgomer commented on lenstronomy/Data/kinematic_bin_2D.py
> +        for idx, value in enumerate(self._data):
I'm not sure how to do this faster? The mask isn't boolean- each pixel is an integer that identifies the bin, so I have to loop over these indices, don't I?

2023-07-31 17:12 UTC, mattgomer commented on lenstronomy/Data/kinematic_data_2D.py
> +class KinData(object):
Removed this class

2023-07-31 20:56 UTC, mattgomer commented on lenstronomy/Util/kin_sampling_util.py
> +    def rotateHST_into_kinNN(self, HST_x, HST_y, ellipse_PA_to_hstx_angle,
This part exists because we have imaging data in "HST" coordinates, and kinematic data in "MUSE" coordinates, which you can relate to one another through RA and DEC. Furthermore, we have the lens model, which is in HST coordinates (imaging model), and might be off center or with a misaligned PA compared to this coordinate systems. The NN returns a model aligned with the x axis, so this must be rotated into the same as the MUSE system, but that rotation and translation depends on the lens model PA, which relates it to the HST system, then to RA/DEC, then to the MUSE system to be interpolated.

2023-07-31 20:58 UTC, mattgomer commented on lenstronomy/Util/image_util.py
> +    querries scipy.ndimage.shift routine
How does this work exactly? I tried pip install sphinx and typed in the terminal "make docs" and it gives me a bunch of messages saying XXX.rst already exists. When I try to open for example Sampling.Likelihoods.rst, I don't see the kinematic sampling there, so I don't think it generated the up-to-date docs.

2023-07-31 20:59 UTC, mattgomer commented on test/test_Util/coolest_template_update_pyAPI.json
> +                    "value": 0.014766053302355864
No idea. Maybe @LyneVdV can help? Is coolest up to date for lenstronomy? Have I perhaps pushed a different version?

2023-08-01 15:11 UTC, mattgomer commented on lenstronomy/Sampling/likelihood.py
> +            if kwargs_model['lens_light_model_list'][kin_lens_light_idx] not in ['SERSIC_ELLIPSE_Q_PHI']:
We have the same problem because we allow for the mass q to be different than the light q, so both need sampled separately.

2023-08-01 15:14 UTC, mattgomer commented on lenstronomy/Util/image_util.py
> +def shiftImage(img, shift):
fixed, but I'm not entirely sure that shift_image is ever used. I don't see any usage cases aside from the test.

2023-08-01 18:36 UTC, mattgomer commented on lenstronomy/Data/kinematic_bin_2D.py
> +
Can you give an example of what you mean by this? Maybe another part of the code I can adapt? As I understand, the point is to assign these parameters without calling class(inputs).data and instead it would just be class.data, for example. But when the class is initialized, it is given bin_data as an argument, so the inputs are required at some point, right?

2023-08-01 18:38 UTC, mattgomer commented on test/test_Sampling/test_Likelihoods/test_kinematic_2D_likelihood.py
> +            #test  that doubling variance decreases logL by factor of 2
Added a test that when one of the vrms bin values is increased by 1 sigma, the likelihood changes by 1 sigma. Not sure if this is what you mean. If you want to put an input parameter off by 1 sigma, that's hard to define. What is the a priori sigma on r_eff, for example? Rather, that sigma is estimated by sampling logL, right?

2023-08-01 18:42 UTC, mattgomer commented on lenstronomy/Sampling/Likelihoods/kinematic_NN_call.py
> +        training_abs_bounds = {'q_mass': [0.6, 1.0],
I've partially fixed this by adding a SKiNN_1.0_config.json file. Right now I added it to Likelihoods because I'm not sure where else to put it. This reads the NN absolute bounds from this file which can be switched out if needed. This file also gives the grid settings of the NN when imported.

The reason this issue is only partially solved is because of some bounds which are expressed in terms of others. For example, the inclination must be greater than arccos(q_light) and arccos(q_mass), meaning its bounds are a rather involved function of the other parameters. I don't see how to include this in the json file, so it's still hardcoded.

2023-08-01 18:43 UTC, mattgomer commented on lenstronomy/Sampling/Likelihoods/kinematic_2D_likelihood.py
> +        self.kinNN_input = {'deltaPix':0.02, 'image': np.ones((551,551))}
Cleared up that this is initializing the classes that run the NN function and the grid alignment/rotation. That self.kinNN_input line now imports settings from the new SKiNN_1.0_config.json file. See comment below.

2023-08-01 19:00 UTC, mattgomer commented
Hi @sibirrer. I've implemented most of these changes and left comments on some of the specifics that may not yet be entirely resolved. Coverage is better as well, but may still have room for improvement. Please take a look through and tell me what you think or if you have any more suggestions. Thanks!

2023-08-07 19:07 UTC, sibirrer commented on lenstronomy/Util/kin_sampling_util.py
> +    def rotateHST_into_kinNN(self, HST_x, HST_y, ellipse_PA_to_hstx_angle,
perhaps then re-name the HST and MUSE parts? Also, HST is a bit ambitious, because it does not necessarily has to correspond to the pixel axes as we can define arbitrary rotations and shifts of the coordinate system in the pixel data

2023-08-08 08:52 UTC, LyneVdV commented on test/test_Util/coolest_template_update_pyAPI.json
> +                    "value": 0.014766053302355864
since this is the _update_ file of the coolest interface (the file saving the results from a modeling procedure), I would assume that running all the tests (which includes the coolest tests) simply rewrite a new answer in the file each time. I agree this has nothing to do with SKiNN, it's just because at some point we must have launched al the tests and not just the ones related to SKiNN to see if everything works and that overwrote the value in that file.

2023-08-14 18:54 UTC, sibirrer reviewed
Looks really good! Thank you @mattgomer !
I am still wondering about the test coverage.
Can you run 
$`make coverage `
locally (and pip install coverage, if not installed) to get a test coverage report locally, since the individual files are not displayed.
Let me know if you have questions. Sorry for being a bit slow atm

2023-08-15 15:18 UTC, mattgomer commented
@LyneVdV When I run make coverage, I get these coolest errors now, which look like 
`FAILED test/test_Util/test_coolest.py::TestCOOLESTinterface::test_load - AttributeError: 'COOLEST' object has no attribute 'exclude_keys'` 
Could I have the wrong version of COOLEST or something? Do you get these errors?

2023-08-16 08:34 UTC, LyneVdV commented
> @LyneVdV When I run make coverage, I get these coolest errors now, which look like `FAILED test/test_Util/test_coolest.py::TestCOOLESTinterface::test_load - AttributeError: 'COOLEST' object has no attribute 'exclude_keys'` Could I have the wrong version of COOLEST or something? Do you get these errors?

I don't have that error (all the test works well...) but I see where it may be coming from .

2023-08-18 19:25 UTC, mattgomer commented on lenstronomy/Util/kin_sampling_util.py
> +    def rotateHST_into_kinNN(self, HST_x, HST_y, ellipse_PA_to_hstx_angle,
Changed the names from HST and MUSE to imaging and spectra

2023-08-18 20:18 UTC, mattgomer commented
@sibirrer I tried make coverage, but had to remove test_coolest.py because it was throwing errors, see #497. When I make the coverage, it looks much better. Total coverage is 92%, kinematic_2D_likelihood is 96%, kinematic_NN_call is 94%. The remaining lines are exceptions if SKiNN is not installed properly, which I'm not entirely sure how to test.

Still having some problems making the docs. I thought I fixed the docstring issue with this commit, but I'm not sure now when viewing differences on the browser. It looks fine on the version I pushed, but I'd like to make the docs to be sure. Last issue I think is the staticmethod issue, which I was wondering if there's an example I can adapt?

2023-08-20 16:25 UTC, sibirrer commented on lenstronomy/Data/kinematic_bin_2D.py
> +
here is an example: https://github.com/lenstronomy/lenstronomy/blob/719a81c992fb0c7302e81163181432ea3a94fd51/lenstronomy/LensModel/Profiles/nfw.py#L127

basically, it means that the definition can also be called outside of the class (since it does not rely on any self. variables of the class itself). Don't forget to remove self from the input argument

2023-08-20 16:27 UTC, sibirrer commented
Thank you @mattgomer ! I merged @LyneVdV 's PR on COOLEST, so I hope if you pull the main into your PR and re-run the tests, it hopefully works. Also, on the CI platform, the tests run, so that's mostly what I care :)

2023-08-21 16:27 UTC, sibirrer approved these changes

2023-08-21 16:28 UTC, sibirrer commented
Looks great @mattgomer !
@ajshajib: this PR is supposed to be merged soon and that might (again) conflict your black formatting. Feel free to merge either one in the sequence you prefer

2023-08-21 16:33 UTC, ajshajib commented
@sibirrer, I will try merging #502 first, and then I can run the formatter on this PR myself to resolve any conflicts. 💪

2023-08-21 17:35 UTC, ajshajib commented
The test failed. Looks like it has to do with merging involving the earlier PR on `nautilus`.  I will do a couple of reverts now and try another way to merge #502 and this PR.

2023-08-21 19:31 UTC, merged