Implement cored and truncated nfw profile
lenstronomy/lenstronomy pull request #494
Opened 2023-08-10 18:00 UTC by dangilman

I add an NFW-like mass profile with a core radius and a truncation radius. I got analytic expressions for the projected mass and the integral of the projected mass by moving the square inside the parenthesis in the denominator, i.e. (1+x^2) instead of (1+x)^2. The core is implemented through a term (r_c^2 + r^2)^1/2, and the profile drops like 1/r^5 outside the truncation radius.

2023-08-10 22:45 UTC, sibirrer requested changes
Looks great! I have only some minor documentation requests.
I guess this is a new profile and perhaps you can leave a reference to a forthcoming publication or so?

2023-08-11 04:09 UTC, dangilman commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +        deflection angel of NFW profile (times Sigma_crit D_OL) along the projection to coordinate 'axis'
fixed

2023-08-11 04:09 UTC, dangilman commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +    def nfwAlpha(self, R, Rs, rho0, r_core, r_trunc, ax_x, ax_y):
done

2023-08-11 04:10 UTC, dangilman commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +    For r_c -> 0 and r_t -> infinity, this profile reduce to something like an NFW profile with the squared term in
So I'm not actually sure how to format it, but I tried. Can you have a look?

2023-08-11 04:10 UTC, dangilman commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +
done

2023-08-11 04:12 UTC, dangilman commented
by the way, in this pull request I edited the MultiPatchReconstruction class to fix an issue I encountered where the code crashes when the pixel coordinate corresponding to each patch is not quite an integer. I fixed it by forcing them to be ints

2023-08-11 04:29 UTC, dangilman commented on lenstronomy/Plots/model_band_plot.py
the change here fixes an issue where sometimes the image labels don't show

2023-08-11 12:54 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +    For
I was more thinking of " For :math:`\\r_c \\rightarrow 0` ..." In that way you can embed lateX in text and not as a formula

2023-08-11 16:20 UTC, dangilman commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +    For
ok, how about now?

2023-08-11 17:50 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/nfw_core_truncated.py
> +    For
oh, you need to keep the parentheses, they got converted here unfortunately. See e.g. https://github.com/lenstronomy/lenstronomy/blob/b9d03df087c846566eb9be777cc2e9a0a7e8a751/lenstronomy/LensModel/Profiles/epl.py#L21

2023-08-11 19:53 UTC, sibirrer commented
Thank you @dangilman ! According to coveralls, there are 8 lines missing to be tested in the new profile (unfortunately, it does not show up). Perhaps you can run 
$make coverage
locally to see the full coverage report

2023-08-11 21:03 UTC, dangilman commented
> Thank you @dangilman ! According to coveralls, there are 8 lines missing to be tested in the new profile (unfortunately, it does not show up). Perhaps you can run $make coverage locally to see the full coverage report

ok, what command do I enter in the terminal to do this?

2023-08-11 21:18 UTC, sibirrer commented
> > Thank you @dangilman ! According to coveralls, there are 8 lines missing to be tested in the new profile (unfortunately, it does not show up). Perhaps you can run $make coverage locally to see the full coverage report
> 
> ok, what command do I enter in the terminal to do this?

`make coverage`

this will execute these lines in the make file: https://github.com/lenstronomy/lenstronomy/blob/b9d03df087c846566eb9be777cc2e9a0a7e8a751/Makefile#L36

2023-08-11 22:24 UTC, dangilman commented
> I got this error... 

<img width="463" alt="Screen Shot 2023-08-11 at 5 24 06 PM" src="https://github.com/lenstronomy/lenstronomy/assets/15677070/d307e0bc-301d-4f40-8f85-b5dff592e549">

2023-08-11 22:30 UTC, dangilman commented
I added some tests trying to guess which lines weren't getting hit... we'll see

2023-08-11 23:27 UTC, sibirrer commented
aside from the test crashing, if you install
pip install coverage
the command should run.

2023-08-14 19:53 UTC, merged