Decoupled multi plane
lenstronomy/lenstronomy pull request #542
Opened 2023-10-25 16:06 UTC by dangilman

I implement an approximation for multi-plane lensing that decouples the deflection angles from the main deflector from deflection from objects between the main lens plane and the source plane (a new pull request because I deleted my remote branch by mistake)

2023-10-25 16:51 UTC, dangilman commented
I also added an example notebook: https://github.com/lenstronomy/lenstronomy-tutorials/blob/main/Notebooks/LensModeling/modeling_with_decoupled_multiplane.ipynb

2023-10-26 15:01 UTC, sibirrer requested changes
Thank you very much! It looks good. I have some minor comments for a bit better documentation in the code itself. It was hard to me to go through it line by line.
And a suggestion to have a SinglePlane lens model being used to be called for the main deflector plane, for convenience and better readability. Thank you very much!

2023-10-26 16:26 UTC, dangilman commented on lenstronomy/LensModel/MultiPlane/decoupled_multi_plane.py
> +        cosmo_bkg = self._multi_plane_base._cosmo_bkg
Yes, I created a new instance of Background in the new class

2023-10-26 16:28 UTC, dangilman commented on lenstronomy/LensModel/MultiPlane/decoupled_multi_plane.py
> +        x = self._x0_interp(coordinates)
the x0_interp is an instance of RegularGridInterpolator that gets passed into the class, and returns comoving coordinates given an angular coordinate. I did it in this way because it is closer to the steps taken in ray_shooting_partial, and eventually I want to expand the class so that you can decoupled lens models at more than one redshift (and have a functioning ray_shooting_partial method)

2023-10-26 16:28 UTC, dangilman commented on lenstronomy/LensModel/MultiPlane/decoupled_multi_plane.py
> +            alpha_x_reduced, alpha_y_reduced = self._multi_plane_base.func_list[
done

2023-10-26 16:29 UTC, dangilman commented on lenstronomy/LensModel/MultiPlane/decoupled_multi_plane.py
> +        alpha_beta_subx = self._alphax_interp_background(coordinates)
renamed to deflection_x_foreground/deflection_y_foreground

2023-10-26 16:29 UTC, dangilman commented on lenstronomy/LensModel/MultiPlane/decoupled_multi_plane.py
> +        alpha_x, alpha_y = (
I commented line by line, let me know what you think

2023-10-26 16:42 UTC, sibirrer approved these changes
Thank you @dangilman !
I approve this PR, just wait until the CI passes.

2023-10-26 19:08 UTC, dangilman commented
hi @sibirrer lets leave this pull request open so I can add the changes to the Sampler class to have different lens models for different observables

2023-10-26 21:34 UTC, dangilman commented
@sibirrer I changed one small block of code in create_class_instances that creates a new lens model for the PointSource class if the keyword arguments are specified. The image position likelihood uses the lens model from the point source class, so this effectively introduces a second lens model for just the lensed point sources. I am testing it out now and it seems to work

2023-12-07 15:38 UTC, closed without merging