User generated light profile in flux ratios calculations
lenstronomy/lenstronomy pull request #548
Opened 2023-11-14 06:34 UTC by basicallymaria

I edited functions that calculated the flux ratios to allow for a more general user input for the source light. Before, the only allowed light profiles were Gaussian and double Gaussian. Now, the functions take in an instance of a light model and its respective keyword arguments. I'm resubmitting the pull request since the previous one had some issues with other files, my fingers are crossed!

2023-11-16 08:41 UTC, dangilman requested changes
Hi @basicallymaria, thanks for making these changes! I suggest removing the source size argument from the function call, as it is only being used to (optionally) estimate the appropriate ray-tracing grid size and resolution. These parameters should instead be specified directly in the function call. I suggest referring to the functions auto_raytracing_grid_size and auto_raytracing_grid_resolution in the documentation for the magnification_finite_adaptive function to guide people for how to choose these parameters. 

Also, as @sibirrer mentioned, you should make sure the test functions pass. This is just a matter of passing in the source model class and kwargs_source parameters to the functions executed in the test suite.

2023-11-16 08:41 UTC, dangilman commented on lenstronomy/LensModel/lens_model_extensions.py
> +        source_size_parsec,
I understand why the "source_size_parsec" argument is being passed (with the option of automatically generating the grid size and pixel resolution), but I think it would be better to remove the source_size_parsec argument and ensure the grid_size and grid_resolution are passed explicitly into the function call.

2023-11-16 08:41 UTC, dangilman commented on lenstronomy/LensModel/lens_model_extensions.py
> +        :param grid_resolution: (optional) the grid resolution in units arcsec/pixel; if not specified, an appropriate value will
make this argument mandatory. You can put in the documentation that the functions auto_raytracing_grid_size/auto_raytracing_grid_resolution give good estimates for the appropriate parameter choices

2023-11-16 08:41 UTC, dangilman commented on lenstronomy/Plots/plot_quasar_images.py
> +    :param source_size: the size of the background source [units parsec]
same comment as above, force users to specify the grid size and grid resolution before calling the function

2023-11-16 08:41 UTC, dangilman commented on lenstronomy/Util/magnification_finite_util.py
>      if grid_radius_arcsec is None:
same comment as above; remove these lines and point users towards these functions in the documentation

2023-12-04 00:47 UTC, basicallymaria commented
Hi @dangilman and @sibirrer  and thank you for your patience! Took longer than I'd hoped, but I edited the corresponding test functions and found that I also had to edit another function (magnification_finite_adaptive). Following your feedback I was able to pass the tests locally before uploading the new edits.

2023-12-06 17:38 UTC, ajshajib commented
@dangilman, @sibirrer, it's because @basicallymaria's topic branch is behind the `main` branch by many commits. @basicallymaria, please pull or sync with the main branch into your `user-generated_light_profile` branch, then `codecov` would work.

2023-12-06 18:54 UTC, ajshajib commented
@dangilman, I went ahead and synced `lenstronomy:main` with @basicallymaria's topic branch. Codecov works now. Please check and proceed as appropriate.

2023-12-06 18:56 UTC, merged