add new EPL + 2 multipole profiles
lenstronomy/lenstronomy pull request #550
Opened 2023-11-17 17:22 UTC by dangilman

I implement an EPL profile with two multipole terms concentric with the EPL origin

2023-11-18 18:02 UTC, dangilman commented
@sibirrer all tests and coverage tests pass

2023-11-18 18:06 UTC, sibirrer requested changes
Looks good. I found some minor typos, formatting issue and perhaps the documentation of the multipole parameters can be improved by adding an equation

2023-11-18 18:06 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +    """EPL (Elliptical Power Law) mass profile combined with two multiple terms of order
'multipole'

2023-11-18 18:06 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +    lenstrnomy.LensModel.Profiles.multipole for details.
lenstronomy typo

2023-11-18 18:06 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +    :param a3_a: Strength of the deviation from elliptical isodensity contours caused by the multipole term of order 3
can you do more documentation of the multipoles or refer to the specific equations if there are elsewhere?

2023-11-18 18:06 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        x-coordinate in image plane :param y: y-coordinate in image plane :param
some docstrings got messed up here

2023-11-18 18:42 UTC, dangilman commented
> Looks good. I found some minor typos, formatting issue and perhaps the documentation of the multipole parameters can be improved by adding an equation

I made the requested changes, some formatting issue is preventing it from passing? not sure what's going on

2023-11-18 18:45 UTC, sibirrer commented
Perhaps you can run the formatter locally? (make sure you update your docformatter):
```
flake8 lenstronomy test
black .
docformatter -r ./* --black --in-place
```

2023-11-18 19:03 UTC, dangilman commented
> Perhaps you can run the formatter locally? (make sure you update your docformatter):
> 
> ```
> flake8 lenstronomy test
> black .
> docformatter -r ./* --black --in-place
> ```

I pulled the automatic formatting changes done on the pull request back to my local machine, and they are causing the weird formatting issues. The format looks correct on my branch

2023-11-18 19:42 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
>      preserves the shape of the isodensity contours such that a3_a produces the same shape regardless of theta_E or q.
@dangilman, looks like you have put new lines in between lines of parameter definitions. This is most likely throwing the `docformatter` off.

2023-11-18 19:46 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
>      preserves the shape of the isodensity contours such that a3_a produces the same shape regardless of theta_E or q.
I think, if you reformat this docstring by hand without the new lines as before, `docformatter` would be able to format it, if still necessary, for the test to pass.

2023-11-18 23:38 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +    :param delta_phi_m4: angle of the m=4 multipole profile relative to the position angle of the EPL profile
```suggestion
    :param theta_E: Einstein radius
    :param gamma: negative power-law slope of the 3D mass distributions
    :param e1: eccentricity. For details, read lenstronomy.Util.param_util.phi_q2_ellipticity document.
    :param e2: eccentricity. For details, read lenstronomy.Util.param_util.phi_q2_ellipticity document.
    :param center_x: center of distortion
    :param center_y: center of distortion
    :param a3_a: Strength of the deviation from elliptical isodensity contours caused by the multipole term of order 3. For details regarding the multipole mass profile see documentation in the class lenstronomy/LensModel/Profiles/multipole.py. The multipole amplitude set by a3_a is translated into the multipole strength from the MULTIPOLE class through a rescaling by theta_E / sqrt(q). This rescaling preserves the shape of the isodensity contours such that a3_a produces the same shape regardless of theta_E or q.
    :param delta_phi_m3: angle of the m=3 multipole profile relative to the position angle of the EPL profile
    :param a4_a: Strength of the deviation from elliptical isodensity contours caused by the multipole term of order 4. For details regarding the multipole mass profile see documentation in the class lenstronomy/LensModel/Profiles/multipole.py. The multipole amplitude set by a4_a is translated into the multipole strength from the MULTIPOLE class through a rescaling by theta_E / sqrt(q). This profile is disky when a4_a>0 and boxy when a4_a<0 for phi_m_a4a=0.0.
    :param delta_phi_m4: angle of the m=4 multipole profile relative to the position angle of the EPL profile
```

2023-11-18 23:38 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        :return: gravitational potential in units of theta_E^2."""
```suggestion
        """Computes the gravitational potential in units of theta_E^2 
        
        :param x: x angular coordinate 
        :param y: y angular coordinate 
        :param theta_E: Einstein radius 
        :param gamma: log-slope of EPL mass profile 
        :param e1: ellipticity of EPL profile (along 1st axis) 
        :param e2: ellipticity of EPL profile (along 2nd axis)
        :param a3_a: amplitude of the m=3 multiple deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m3: orientation of the m=3 profile relative to the position angle of the EPL profile 
        :param a4_a: amplitude of the m=4 multipole deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m4: orientation of the m=4 profile relative to the position angle of the EPL profile
        :param center_x: center of the profile :param center_y: center of the profile
        :return: gravitational potential in units of theta_E^2."""
```

2023-11-18 23:38 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        :return: deflection angles in units of theta_E."""
```suggestion
        """Compute the derivatives of the potential in units of theta_E 
        :param x: x angular coordinate 
        :param y: y angular coordinate 
        :param theta_E: Einstein radius 
        :param gamma: log-slope of EPL mass profile 
        :param e1: ellipticity of EPL profile (along 1st axis) 
        :param e2: ellipticity of EPL profile (along 2nd axis)
        :param a3_a: amplitude of the m=3 multiple deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m3: orientation of the m=3 profile relative to the position angle of the EPL profile 
        :param a4_a: amplitude of the m=4 multipole deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m4: orientation of the m=4 profile relative to the position angle of the EPL profile
        :param center_x: center of the profile 
        :param center_y: center of the profile
        :return: deflection angles in units of theta_E."""
```

2023-11-18 23:38 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        center of the profile :return: components of the hessian matrix."""
```suggestion
        """Compute the second derivatives of the potential that enter the Hessian matrix.
        
        :param x: x angular coordinate 
        :param y: y angular coordinate 
        :param theta_E: Einstein radius 
        :param gamma: log-slope of EPL mass profile 
        :param e1: ellipticity of EPL profile (along 1st axis) 
        :param e2: ellipticity of EPL profile (along 2nd axis) 
        :param a3_a: amplitude of the m=3 multiple deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m3: orientation of the m=3 profile relative to the position angle of the EPL profile 
        :param a4_a: amplitude of the m=4 multipole deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q)
        :param delta_phi_m4: orientation of the m=4 profile relative to the position angle of the EPL profile 
        :param center_x: center of the profile 
        :param center_y: center of the profile 
        :return: components of the hessian matrix."""
```

2023-11-18 23:41 UTC, ajshajib commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        :return: deflection angles in units of theta_E."""
```suggestion
        """Compute the derivatives of the potential in units of theta_E 
        
        :param x: x angular coordinate 
        :param y: y angular coordinate 
        :param theta_E: Einstein radius 
        :param gamma: log-slope of EPL mass profile 
        :param e1: ellipticity of EPL profile (along 1st axis) 
        :param e2: ellipticity of EPL profile (along 2nd axis)
        :param a3_a: amplitude of the m=3 multiple deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m3: orientation of the m=3 profile relative to the position angle of the EPL profile 
        :param a4_a: amplitude of the m=4 multipole deviation from pure elliptical shape related to the physical amplitude of the MULTIPOLE profile by a scaling theta_E / sqrt(q) 
        :param delta_phi_m4: orientation of the m=4 profile relative to the position angle of the EPL profile
        :param center_x: center of the profile 
        :param center_y: center of the profile
        :return: deflection angles in units of theta_E."""
```

2023-11-19 17:43 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        :return: deflection angles in units of theta_E."""
@ajshajib amazing! thanks

2023-11-20 17:54 UTC, dangilman commented
@sibirrer It appears that the formatting issues have been resolved

2023-11-20 17:58 UTC, ajshajib commented on lenstronomy/LensModel/Solver/solver4point.py
> +            "'EPL_MULTIPOLE_M3M4'",
```suggestion
            "EPL_MULTIPOLE_M3M4",
```

2024-03-01 17:06 UTC, dangilman commented
This lens profile was implemented through the decoupled multi-plane formalism pull request, so I'll close this pull request.

2024-03-01 17:06 UTC, closed without merging