Add tracer types, allowing metallicity data to be used in observer units.
lenstronomy/lenstronomy pull request #585
Opened 2024-02-14 02:57 UTC by astrobenji

Adds a new parameter, "tracer_type", to the tracer module. If this is linear, components are added linearly. If this is metallicity, then the metallicity in units of log(O/H)+12 is first converted to linear units, then added, then converted back into convenient logarithmic units. The default setting for tracers is still linear.

2024-02-14 03:23 UTC, sibirrer requested changes
Thank you @benmetha. I have one request to change, and then there are no tests for the  newly added component. Can you write a test function that will call this feature and test it? You can have a look at the test folder of the tracer_model. Thank you!

2024-02-14 03:23 UTC, sibirrer commented on lenstronomy/ImSim/tracer_model.py
> +        :param tracer_type: LINEAR or METALLICITY; to determine how tracers are summed between components, as metallicities
can you rename the type to LOG instead of METALLICITY? This is more explicitly, and it might not always be true that when you have line ratios, that you want to sum them in log space (the units of metallicity are log, but you can also define a linear line ratio unit)

2024-02-19 00:43 UTC, sibirrer requested changes
Thank you very much! It looks good and thanks also for the test.
There is an issue with the formatting in the test file. Hope you can solve it either manually or through the terminal running black

2024-02-19 00:43 UTC, sibirrer commented on test/test_ImSim/test_tracer_model.py
> +     (1) using the tracer_type="LOG" argument (2) converting units to linear ones, using
something is odd here with the re-formatting (the pre-commit also failed). Can you check on this and perhaps run black locally with

```
black .
docformatter -r ./* --black --in-place
```

2024-02-19 01:07 UTC, sibirrer requested changes

2024-02-19 01:07 UTC, sibirrer commented on test/test_ImSim/test_tracer_model.py
> +     (1) using the tracer_type="LOG" argument
you need to move these strings one tab inwards, and perhaps not having a blank line in-between

2024-02-19 01:17 UTC, sibirrer commented on test/test_ImSim/test_tracer_model.py
> +    """Convolve a tracer with log units with a surface brightness profile in two ways:
sorry, mixed up inwards vs outwards. Everything needs to be aligned with the code block that is in the definition (see all other docstrings)

2024-02-19 01:38 UTC, sibirrer commented
@benmetha the two tests failed, see the link to the Tests/build

2024-02-19 04:20 UTC, sibirrer commented
Thank you very much @benmetha! I see that the de_lens=True option in the _tracer_model_source() definition has not been tested. Can you please add a test that executes this part. I doubt that it fails but this is just to make sure that this feature gets preserved by future development - thank you!

2024-02-19 04:31 UTC, astrobenji commented
Hi Simon, I never wrote the code for the `de_lens` option. I don't know how it is used. If you'd like, I could look into how its used in some of the other test cases that test image simulation, and try to write something that uses this option for traced quantities? But I don't understand how making a test case for that feature is related to this pull request.

2024-02-19 12:48 UTC, merged