Decoupled-multiplane
lenstronomy/lenstronomy pull request #592
Opened 2024-02-23 20:38 UTC by dangilman

Trying this again...

2024-02-26 23:17 UTC, dangilman commented
@sibirrer I also added the example notebook with pull request #26 to lenstronomy-tutorials

2024-02-27 01:02 UTC, sibirrer requested changes
Looks very good. I have a few minor requests regarding documentation. Thank you very much @dangilman !

2024-02-27 05:28 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/optimizer.py
> +        :param ray_shooting_class:
fixed

2024-02-27 05:28 UTC, dangilman commented on lenstronomy/LensModel/QuadOptimizer/optimizer.py
> +        :param x_image:
fixed

2024-02-27 05:28 UTC, dangilman commented on lenstronomy/LensModel/Util/decouple_multi_plane_util.py
> +    grid_size, grid_resolution, coordinate_center_x=0.0, coordinate_center_y=0.0
fixed

2024-02-27 05:29 UTC, dangilman commented on lenstronomy/LensModel/Util/decouple_multi_plane_util.py
> +def class_setup(
renamed to decoupled_multiplane_class_setup

2024-02-27 05:29 UTC, dangilman commented on lenstronomy/Plots/model_band_plot.py
> +        super_sample_factor=None,
fixed

2024-02-27 06:34 UTC, dangilman commented on lenstronomy/LensModel/Util/decouple_multi_plane_util.py
> +    """Creates grids for use in the decoupled multiplane model.
I guess in principle this could be accomplished with the make_grid function, but the inputs are different (deltaPix and numPix instead of grid_size and grid_resolution). It shouldn't depend on the data coordinate system though

2024-02-28 17:39 UTC, dangilman commented
@sibirrer I think I've addressed most of your comments, anything you would like for me to check?

2024-02-28 22:15 UTC, sibirrer requested changes
Thank you @dangilman! There are few docstrings that did not format appropriately. most likely due to a missing blank line between general description and parameter descriptions

2024-02-28 22:15 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        """Computes the gravitational potential in units of theta_E^2 :param x:
there are some formatting that got a hiccup

2024-02-28 22:15 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m3m4.py
> +        potential) :param x: x-coordinate in image plane :param y: y-coordinate in image
I think you need a blank line between the text and the :param : statements

2024-02-28 22:15 UTC, sibirrer commented on lenstronomy/LensModel/QuadOptimizer/optimizer.py
> +        """Initializes the Optimizer class using the decoupled multi-plane formalism for
dito

2024-02-28 22:15 UTC, sibirrer commented on lenstronomy/LensModel/Util/decouple_multi_plane_util.py
> +    :param lens_model_fixed: an instance of LensModel that is static :param
documentation without new line

2024-02-28 22:15 UTC, sibirrer commented on lenstronomy/LensModel/Util/decouple_multi_plane_util.py
> +    decoupled multi-plane approxiamtion for the specified lens model :param
blank line needed

2024-02-29 03:20 UTC, sibirrer commented on lenstronomy/LensModel/QuadOptimizer/optimizer.py
> +        """This function evaluates a metric that determines goodness of fit :param
here are also some formatting issues

2024-03-01 00:34 UTC, sibirrer approved these changes
Looks great, thank you! Feel free to merge it once the tests pass

2024-03-01 00:37 UTC, merged