Create and Add Adaptive Boundary Mesh
lenstronomy/lenstronomy pull request #604
Opened 2024-04-14 06:27 UTC by avlando

Implements an Adaptive Boundary Mesh (ABM) algorithm to achieve high-resolution microlensing simulations. Gravitational lensing effects caused by point mass lens and elliptical source. ABM algorithm dynamically adapts the mesh resolution around the source, efficiently capturing lensed image for M0 = 0.01M_sol to 0.1M_sol.

2024-04-14 16:19 UTC, sibirrer requested changes
Thank you very much Alex! I have some minor suggestions/requests. Primarily that you should not have lines of code outside of definitions for the user to use. Think of this routines being the software that you (or any user) import on your notebook to facilitate the tasks you want to calculate

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +import itertools
convention on file names and folders. File names are lower_case, folder names are UpperCase

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +    :param center: nparray; center of square
a slightly better convention for the documentation strings is using the explicit :type <param_name>: convention
:param center: center of square
:type center: nparray

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +# define the microlens
all these lines of code that are not a function/definition I would suggest not having in the software package, or in the form of functions. The idea is that the user has full control over those and not being hard coded in a software package. You can keep using a notebook for your investigations using functions the functions from this file

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +L = (
do you want these settings for example as default settings in your ABM function, or even be part of the high-level function for the user?

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +
can you provide the docstrings for this definition and the input and output variables as well?

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +    test_point = np.array(test_point)
since you require in the input statement that test_point and center_points are already numpy arrays, you don't need to explicitly convert those (in fact, this could possibly take quite a bit of computational cost)

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +    """Returns list of those high resolution image-plane pixels that were mapped to
this routine goes through an iterative adaptive process. Can you link to the original paper that introduced this algorithm?

2024-04-14 16:19 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/ABM.py
> +# compute unlensed surface brightness
can you either define a function(s) for this task or move those to a jupyter notebook (not to be committed for now)

2024-04-15 08:11 UTC, avlando commented on lenstronomy/LensModel/Microlensing/ABM.py
> +import itertools
that is a python module like numpy, voided from code (used in previous commit)

2024-04-15 09:13 UTC, avlando commented on lenstronomy/LensModel/Microlensing/ABM.py
> +L = (
I have added them into the ABM function with comments

2024-04-24 00:36 UTC, sibirrer requested changes
The tests are failing due to incomplete import statements. Check my comments and I hope the automatic tests will then pass

2024-04-24 00:36 UTC, sibirrer commented on test/test_LensModel/test_Microlensing/test_ABM.py
> +from Microlensing.adaptive_boundary_mesh import loop_information
you have to use here the full lenstronomy paths, i.e. from lenstronomy.LensModel.Micorlensing.... import

2024-04-24 15:30 UTC, sibirrer requested changes
some minor comments on the documentation

2024-04-24 15:30 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/adaptive_boundary_mesh.py
> +    :param eta: 0.7 * n_p
define what eta is as the input of this function, not how another function defined it prior to input of this function

2024-04-24 15:30 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/adaptive_boundary_mesh.py
> +    :param eta: 0.7 * n_p
define what eta is, not what input relations are used by users

2024-06-17 20:56 UTC, sibirrer requested changes
Thank you! I have one comment/request that came up looking at the test coverage

2024-06-17 20:56 UTC, sibirrer commented on lenstronomy/LensModel/Microlensing/adaptive_boundary_mesh.py
> +        elif i == number_of_iterations:
looking at the test coverage, it worries me that this line is not being tested. Can you check (and modify if needed) that this criteria is applied at the very last iteration?

2024-06-20 07:59 UTC, avlando commented on lenstronomy/LensModel/Microlensing/adaptive_boundary_mesh.py
> +        elif i == number_of_iterations:
changed main loop to include final iteration, counter now starts at 2 to avoid extra iteration at end.

2024-06-20 12:08 UTC, sibirrer approved these changes
Thank you very much @avlando !

2024-06-20 17:51 UTC, sibirrer approved these changes
wohooo!

2024-06-20 17:51 UTC, merged