Simple line segment LightModel for jet modeling
lenstronomy/lenstronomy pull request #611
Opened 2024-05-19 19:39 UTC by michael7198

Hi all,

I've added a very simple line segment LightModel in order to facilitate modeling lensed AGN jets. In its current state the model simply produces a constant surface brightness rectangle, which could be used for a naive continuum subtraction. I'd very much appreciate input on how to structure tests for an addition like this, as well as any other general feedback. As implemented the model is pixel-based and therefore much less smooth than other light profiles, and I understand that could be a potential issue.

Thanks!

-Michael

2024-05-20 13:19 UTC, sibirrer requested changes
Hi @michael7198 thank you very much for the PR! It looks compatible with lenstronomy.
Now for testing, have a look at the test/test_LightModel/test_Profiles folder where for each light profile, there should be a test file. The idea is to test the specific functions with some known input-output behavior and see whether they execute.

And then you should test that the model can be properly integrated in LightModel, in the test_LightModel/test_light_model.py file

Let us know if you have questions!

2024-05-20 13:19 UTC, sibirrer commented on lenstronomy/LightModel/Profiles/lineprofile.py
> +        return amp * (x_ > 0) * (x_ < length) * (abs(y_) < width / 2)
does this work when you are outside the bounds? I would suggest you use array convention and explicitly set it to zero outside the bounds, and amp inside it.

2024-05-20 13:19 UTC, sibirrer commented on lenstronomy/LightModel/Profiles/lineprofile.py
> +    """Horizontal line segment class."""
might be worth describing this class a bit better

2024-05-20 13:19 UTC, sibirrer commented on lenstronomy/LightModel/light_model_base.py
> +    "LINEPROFILE",
I'd suggest you naming it LINE_PROFILE instead for better readability

2024-05-20 15:35 UTC, michael7198 commented on lenstronomy/LightModel/Profiles/lineprofile.py
> +        return amp * (x_ > 0) * (x_ < length) * (abs(y_) < width / 2)
I believe I've done this (created an array of zeros, then made a mask that selects elements in the bounds and sets them to amp) but let me know if you meant something else by "array convention".

2024-05-20 20:27 UTC, sibirrer requested changes
Looks great. I have one minor request in testing and then it should be good to go.

2024-05-20 20:27 UTC, sibirrer commented on test/test_LightModel/test_Profiles/test_lineprofile.py
> +        x = np.array([0, 1, 0.5*np.cos(np.deg2rad(57))])
can you make a test with an array structure (you did this) and a single-valued input? Thank you!

2024-05-20 20:51 UTC, michael7198 commented
I've added a test to the test_profiles folder but am not sure what to do with the test_light_model.py file. For now I've added the model and its kwargs where relevant under self.setup_method and self.test_total_flux.

2024-05-20 20:51 UTC, michael7198 commented on test/test_LightModel/test_Profiles/test_lineprofile.py
> +        x = np.array([0, 1, 0.5*np.cos(np.deg2rad(57))])
Done!

2024-05-21 12:29 UTC, sibirrer commented
There are errors in the test @michael7198. Check out the link above. You can also execute these tests locally, by typing e.g.:
$ py.test test/test_LightModel

2024-05-21 15:55 UTC, sibirrer approved these changes

2024-05-21 17:01 UTC, merged