Starred integration
lenstronomy/lenstronomy pull request #615
Opened 2024-05-29 19:20 UTC by martin-millon

This is a tentative to incorporate the STARRED PSF reconstruction algorithm into lenstronomy. This is not ready yet but I am opening this merge request to see if there is any conflict with the main branch.

2024-05-31 18:11 UTC, sibirrer requested changes
Thank you very much @martin-millon! I have one request to raise errors for features that are not (yet) supported with STARRED iterations, as otherwise this is not transparently presented to the user

2024-05-31 18:11 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +            # todo: masks are not used here, but could be implemented in the future
can you perhaps make a raise statement if masks were provided? In that form it is transparent for the user. Otherwise they might switch to STARRED pdf reconstruction and things can go south without a masked treatment

2024-05-31 18:28 UTC, martin-millon commented on lenstronomy/Workflow/psf_fitting.py
> +            # todo: masks are not used here, but could be implemented in the future
Do you mean the mask provided for the lens model? Or specific masks only for the PSF fitting? 
I can actually add the masks, this is supported by STARRED, so this should not be an issue.

2024-05-31 18:30 UTC, sibirrer commented on lenstronomy/Workflow/psf_fitting.py
> +            # todo: masks are not used here, but could be implemented in the future
I was mostly thinking of the mask for the PSF fitting (but also the model), i.e. the neighbor mask

2024-05-31 23:47 UTC, martin-millon commented on lenstronomy/Workflow/psf_fitting.py
> +            # todo: masks are not used here, but could be implemented in the future
OK, it makes no sense to propagate the corner_masks to starred for the moment. I've added warning messages in a new commit.

2024-05-31 23:48 UTC, martin-millon commented
Let us check why the dependencies are not installed when pip installing starred, this is why the automated tests are failing. It seems to be a bug in the Starred release.

2024-06-01 00:11 UTC, sibirrer commented
> Let us check why the dependencies are not installed when pip installing starred, this is why the automated tests are failing. It seems to be a bug in the Starred release.

sounds good. Ping me when the CI works!

2024-06-05 00:20 UTC, martin-millon commented
The problem is that STARRD requires optax>=0.2.2 for compatibility with the latest JAX version. If I include optax >=0.2.2 in the dependencies of STARRED, the CI pipeline starts to install all versions of matplotlib until it crashes at version 1.4.3 (see the weird error). Any idea why this is happening @sibirrer ?

2024-06-05 00:27 UTC, sibirrer commented
> The problem is that STARRD requires optax>=0.2.2 for compatibility with the latest JAX version. If I include optax >=0.2.2 in the dependencies of STARRED, the CI pipeline starts to install all versions of matplotlib until it crashes at version 1.4.3 (see the weird error). Any idea why this is happening @sibirrer ?

hmm, don't know how to solve this. Might be a bug in the requirements of optax? Do the CI tests for STARRED run? Is the test environment there different? Otherwise down-grade to an older jax version might do it (for the CI)

2024-06-05 04:30 UTC, martin-millon commented
Maybe this is related to this: https://github.com/pypa/pip/issues/9284

2024-06-05 20:54 UTC, martin-millon commented
OK, all tests have passed on my fork of SKiNN. Once this PR is merged https://github.com/mattgomer/SKiNN/pull/2, I can switch the test_requirements to the main branch of SKiNN and this PR can be merged.

2024-06-06 23:20 UTC, martin-millon commented
Matt merged my PR into SKiNN and I switched back to the main SKiNN branch in the test_requirements.txt. This is now ready to be merged.

2024-06-07 12:59 UTC, merged

2024-06-07 12:59 UTC, sibirrer commented
Wohoo!! Thank you very much @martin-millon !