Update to lens_plot.py
lenstronomy/lenstronomy pull request #625
Opened 2024-07-09 17:12 UTC by jocelyn-mcmahon-16

Added feature to lens_plot.py to allow for the plotting of multiple sources/images in the point_source_plot function. Allows for input of parameters _name_list_ and _index_, which respectively specify a new list of labels to be used for the images and, when used with multiple sources, labels each source's images with a number to more easily determine which image comes from which source.

2024-07-09 19:13 UTC, sibirrer requested changes
Looks great, thank you @jocelyn-mcmahon-16 ! I have some suggestions and a request for better test coverage

2024-07-09 19:13 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    name_list=None,
can you document this new input variables in the doc strings

2024-07-09 19:13 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +        name_list = [
this line of code is not tested. Can you add a test that goes through this option?

2024-07-09 19:13 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +        name_list = [
do you really need this line of code? can't you just get name_list = _NAME_LIST and then also go through the for-loop the same way as for custom input for name_list?

2024-07-09 19:13 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +        name_list = name_list
can you also make a test case with this option?

2024-07-10 18:46 UTC, jocelyn-mcmahon-16 commented on lenstronomy/Plots/lens_plot.py
> +        name_list = name_list
Added a test for this one!

2024-07-10 18:46 UTC, jocelyn-mcmahon-16 commented on lenstronomy/Plots/lens_plot.py
> +        name_list = [
I added a test for each case. I also updated it to loop over _NAME_LIST like you suggested, but I left it as a separate case.

2024-07-10 18:47 UTC, jocelyn-mcmahon-16 commented on lenstronomy/Plots/lens_plot.py
> +    name_list=None,
Added the variables!

2024-07-10 21:28 UTC, sibirrer approved these changes
Thank you very much @jocelyn-mcmahon-16 !

2024-07-10 21:28 UTC, merged