Update GaussianEllipseKappaSet to support varying ellipticities and Include in profile list base
lenstronomy/lenstronomy pull request #629
Opened 2024-07-17 14:45 UTC by RosettaGit

This PR modifies the GaussianEllipseKappaSet function in gaussian_decomposition.py to support variable ellipticities for each Gaussian component. This enhancement allows the mass contour to adapt more flexibly to complex scenarios like twists. Users can still specify a single ellipticity for all components in simpler cases. Additionally, this mass profile has been added to profile_list_base under the new class "MULTI_GAUSSIAN_ELLIPSE_KAPPA_CONVERGENCE". The term “CONVERGENCE” refers to the input being a 2D projected mass density map. If anyone has suggestions for a clearer name that could reduce confusion with similar existing MGE profiles, they are welcome! Below is a figure comparing the contour maps from the current lenstronomy kappa map of GaussianEllipseKappaSet and the reconstructed image from the mgefit model. The latter serves as the input for the former, demonstrating their consistency in the plot.
![contour](https://github.com/user-attachments/assets/7cced008-1201-48bf-812f-0ae0b923f23c)

2024-07-17 15:07 UTC, ajshajib commented
@RosettaGit, thanks a lot for the PR! You haven't added the associated test functions for the newly added code. The Codecov report above needs to say that the Patch coverage is 100%. 🙏

2024-07-17 15:07 UTC, ajshajib requested changes
@RosettaGit, thanks a lot for the PR! You haven't added the associated test functions for the newly added code. The Codecov report above needs to say that the Patch coverage is 100%. 🙏

2024-07-17 19:40 UTC, ajshajib commented on lenstronomy/LensModel/profile_list_base.py
> +    "MULTI_GAUSSIAN_ELLIPSE_KAPPA_CONVERGENCE",
```suggestion
    "MULTI_GAUSSIAN_ELLIPSE_KAPPA",
```

2024-07-17 19:40 UTC, ajshajib reviewed
I have suggested a change in the name of the profile.

2024-07-17 23:26 UTC, ajshajib commented
@RosettaGit, I have moved the class `GaussianEllipseKappaSet` to multi_gaussian_ellipse_kappa.py and renamed it to `MultiGaussianEllipseKappa` in #630. Please wait for that PR to be merged and then provide your additions to that file along with the associated tests.

2024-07-18 02:28 UTC, RosettaGit commented
OK I see, Thank you!

2024-07-18 12:10 UTC, ajshajib commented
@RosettaGit, #630 is merged.

2024-07-18 17:11 UTC, closed without merging