Bug fix for lens_plot.py update
lenstronomy/lenstronomy pull request #637
Opened 2024-08-05 15:40 UTC by jocelyn-mcmahon-16

Fixed error regarding indices, updated labeling defaults.

2024-08-06 15:40 UTC, sibirrer commented
@jocelyn-mcmahon-16 there are some tests failing. You can execute the tests locally with e.g. $py.test test/test_Plots

2024-09-02 19:16 UTC, sibirrer commented
@jocelyn-mcmahon-16 just let @ajshajib know when it's ready to be reviewed again. Thank you!

2024-09-03 18:26 UTC, jocelyn-mcmahon-16 commented
Thanks Simon!
@ajshajib  I think this is ready to be reviewed again. Thanks!

2024-09-03 19:44 UTC, ajshajib requested changes
Thanks a lot for the updates! I have made a few suggestions, many of them are already as suggested commits. One way to go forward with implementing the suggestions would be clicking on "Commit suggestion" if you would like to accept the suggestion, then pulling from the remote branch to your local, and then working on your local copy to implement the rest of the suggestions before pushing your local commits to the remote again.

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        name_List_ = _NAME_LIST
```suggestion
        name_list_ = _NAME_LIST
```

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    param color_list: list of strings to represent the color for each source's images. Default None.
```suggestion
    :param color_list: list of strings to represent the color for each source's images. Default "k".
```

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        color,
Here, `ax.plot()` expects a single color, I think, not a list. But, the documentation implies that a list of color strings is being passed.

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    color_list="k",
Corresponding line needs to be added in the docstring.

2024-09-03 19:44 UTC, ajshajib commented on test/test_Plots/test_lens_plot.py
> +                color_list=color_List[i],
```suggestion
                color_list=color_list[i],
```

2024-09-03 19:44 UTC, ajshajib commented on test/test_Plots/test_lens_plot.py
> +            color_List = ["k", "b", "g", "r", "c", "m", "y"]
```suggestion
            color_list = ["k", "b", "g", "r", "c", "m", "y"]
```

2024-09-03 19:44 UTC, ajshajib commented on test/test_Plots/test_lens_plot.py
> +        name_List = [
```suggestion
        name_lists = [
```

2024-09-03 19:44 UTC, ajshajib commented on test/test_Plots/test_lens_plot.py
> +                name_list=name_List[i],
```suggestion
                name_list=name_lists[i],
```

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        ax.text(x_, y_, name_List_[i], fontsize=20, color=color)
I think you can't pass a list of colors here.

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +            name_List_.append(str(index + 1) + name_list[i])
```suggestion
            name_list_.append(str(index + 1) + name_list[i])
```

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        name_List_ = name_list
```suggestion
        name_list_ = name_list
```

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    color_list="k",
If this is a list of colors, the default should be a list, e.g., `["k"]`.

2024-09-03 19:44 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    color_list="k",
The default value should be a list.

2024-09-04 19:07 UTC, ajshajib commented
Hi @jocelyn-mcmahon-16, thanks a lot for the updates. When it's ready for review again, please click on the "Re-request review" button at the top right of this page in the "Reviewers" section.

2024-09-04 19:11 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    color = color_value
```suggestion
```

2024-09-04 19:11 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        ax.text(x_, y_, name_list_[i], fontsize=20, color=color)
```suggestion
        ax.text(x_, y_, name_list_[i], fontsize=20, color=color_value)
```

2024-09-04 19:11 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +        color,
```suggestion
        color_value,
```

2024-09-04 19:14 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +    color_value="k",
```suggestion
    color="k",
```

2024-09-04 19:15 UTC, ajshajib approved these changes
Thanks a lot, @jocelyn-mcmahon-16! I am making some minor changes and will merge the PR after the tests pass.

2024-09-04 19:16 UTC, ajshajib commented on lenstronomy/Plots/lens_plot.py
> +            color_value=color_value,
```suggestion
            color=color_value,
```

2024-09-04 19:53 UTC, merged