M1 multipole in EPL class
lenstronomy/lenstronomy pull request #667
Opened 2024-11-13 06:28 UTC by dangilman

I add a new lens profile class that includes a spherical m=1 multipole perturbation concentric with an EPL profile, an m=3 perturbation, and an m=4 perturbation

2024-11-13 06:44 UTC, dangilman commented
@sibirrer @ajshajib  there seems to be an issue with the build, but the tests are passing, same issue affects another open pull request

2024-11-13 12:34 UTC, sibirrer commented
> @sibirrer @ajshajib there seems to be an issue with the build, but the tests are passing, same issue affects another open pull request

yeah @dangilman, the pre-commit ci is broken. You can ignore that part

2024-11-27 00:49 UTC, sibirrer requested changes
Looks great! I have some very minor comments

2024-11-27 00:49 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +    See also documentation of EPL_BOXYDIKSY CLASS, lenstronomy.LensModel.Profiles.epl
are there references to a paper that uses this parameterization?

2024-11-27 00:49 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +    and lenstrnomy.LensModel.Profiles.multipole for details.
typo in lenstronomy

2024-11-27 00:49 UTC, sibirrer commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +        :param x: x-coordinate in image plane :param y: y-coordinate in image plane
docstrings are duplicated

2024-12-05 17:49 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +    See also documentation of EPL_BOXYDIKSY CLASS, lenstronomy.LensModel.Profiles.epl
not using elliptical multipoles, but there are some papers that use all three circular ones. I can add a reference

2024-12-05 17:49 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +    and lenstrnomy.LensModel.Profiles.multipole for details.
fixed

2024-12-05 18:04 UTC, dangilman commented on lenstronomy/LensModel/Profiles/epl_multipole_m1m3m4.py
> +        :param x: x-coordinate in image plane :param y: y-coordinate in image plane
fixed

2024-12-05 18:28 UTC, closed without merging