add function to ModelPlot to return single band chi square
lenstronomy/lenstronomy pull request #675
Opened 2024-11-25 15:39 UTC by nataliehogg

Short function added to ModelPlot to allow direct access to the single band chi square i.e. `chi2 = model_plot.single_band_chi2(band_index=0)`. This is useful if for example you want to automatically add the chi square value of a model to a plot/legend. I'm not sure if this is already possible or if there's a neater way to do it.

2024-11-25 16:01 UTC, sibirrer commented
@nataliehogg thank you for the PR. There are some code formatting issues

2024-11-26 16:01 UTC, nataliehogg commented
hi @sibirrer I fixed the formatting and added a test for the function

2024-11-26 17:22 UTC, sibirrer requested changes
Thank you @nataliehogg ! I have a comment on accessing a private variable. I suggest you make the variable public

2024-11-26 18:03 UTC, nataliehogg commented on lenstronomy/Plots/model_plot.py
> +        return plot_band._reduced_x2
:+1:  I changed the relevant function in `image_reconstruction.py`

2024-11-26 18:05 UTC, sibirrer approved these changes

2024-11-26 18:06 UTC, merged