Adds the line-of-sight flexion calculation from Duboscq et al. 2024 (2405.12091)
lenstronomy/lenstronomy pull request #677
Opened 2024-11-27 18:03 UTC by nataliehogg

This PR includes the addition of a new sub-module for line-of-sight effects in the beyond-tidal regime, i.e. LOS flexion. The calculations are presented in the paper [Weak lensing of strong lensing: beyond the tidal regime](https://arxiv.org/abs/2405.12091), Duboscq et al. (2024). The sub-module `LineOfSightFlexion` contains the altered `SinglePlane` class, as well as the full and minimal LOS flexion models. These implementations were done by @TheoDuboscq; I added tests for the new models, closely following the tests for `SinglePlaneLOS`. The Hessian and Fermat potential functions are currently untested as I think this requires the calculation of a multiplane equivalent to the single plane flexion.

2025-01-25 09:41 UTC, ajshajib commented
Thanks a lot, @nataliehogg and @TheoDuboscq. Do you plan to increase the test coverage to 100% of of the diff, which we strongly encourage for PRs before being reviewed and merged?

2025-01-25 16:32 UTC, nataliehogg commented
Hi @ajshajib sorry to have left this PR hanging, I plan to increase the coverage when I can! I had thought of constructing a multi-plane equivalent to the LOS flexion to test it in the same way the LOS shear is tested, but I'm not actually sure if that's feasible. I'll discuss with @TheoDuboscq and see what we can come up with.

2025-03-07 23:05 UTC, ajshajib commented on lenstronomy/LensModel/profile_list_base.py
> +    "LOSF",
```suggestion
    "LOS_FLEXION",
```

2025-03-07 23:05 UTC, ajshajib commented on lenstronomy/LensModel/profile_list_base.py
> +    "LOSF_MINIMAL",
```suggestion
    "LOS_FLEXION_MINIMAL",
```

2025-03-07 23:05 UTC, ajshajib commented on lenstronomy/LensModel/profile_list_base.py
> +
```suggestion
```

2025-03-07 23:06 UTC, ajshajib commented on lenstronomy/LensModel/profile_list_base.py
> +
```suggestion
```

2025-03-07 23:08 UTC, ajshajib commented on lenstronomy/LightModel/Profiles/sersic_elliptic_flexed.py
> +class SersicEllipticFlexed(SersicUtil):
```suggestion
class SersicEllipticWithFlexion(SersicUtil):
```

2025-03-08 00:16 UTC, ajshajib commented on lenstronomy/LensModel/LineOfSightFlexion/LOSFlexionModels/losflexion.py
I suggest this file and `losflexion_minimal.py` be moved to the LensModel/LineOfSight/LOSModels folder to avoid too much fragmentation, unless there's a good reason to keep them separate.

2025-03-08 00:28 UTC, ajshajib commented on lenstronomy/LensModel/LineOfSightFlexion/LOSFlexionModels/losflexion_minimal.py
> +
```suggestion
```

2025-03-08 00:29 UTC, ajshajib commented on lenstronomy/LensModel/LineOfSightFlexion/LOSFlexionModels/losflexion_minimal.py
> +    G2_1los, omega_los.
```suggestion
    beyond the tidal regime" (Duboscq et al. 2024, 2405.12091). It is equivalent to LOSFlexion but with fewer parameters (19),
    namely: kappa_od, gamma1_od, gamma2_od, F1_od, F2_od, G1_od, G2_od, kappa_los,
    gamma1_los, gamma2_los, F1_los, F2_los, G1_los, G2_los, F1_1los, F2_1los, G1_1los,
    G2_1los, omega_los.
```

2025-03-08 00:30 UTC, ajshajib commented on lenstronomy/LensModel/LineOfSightFlexion/single_plane_los_flexion.py
Similar to the other comment, this could also be moved to LensModel/LineOfSight.

2025-03-08 00:46 UTC, ajshajib requested changes
Thanks a lot, @nataliehogg and @TheoDuboscq. I have left some suggestions for structuring of the modules and updating a few variable/function names. But, please let me know if there's a reason to keep the module structure as is.

2025-03-08 00:46 UTC, ajshajib commented on lenstronomy/LensModel/LineOfSightFlexion/single_plane_los_flexion.py
> +        self._index_losf = index_losf
It's better for future developers/users to use more descriptive variable name, so I suggest changing the word "losf" to "los_flexion" when it appears in the variable and function names.

2025-03-08 00:46 UTC, ajshajib commented on lenstronomy/LightModel/Profiles/sersic_elliptic_flexed.py
> +class SersicEllipticFlexed(SersicUtil):
The file name should also be changed accordingly.

2025-03-08 00:46 UTC, ajshajib commented on test/test_LensModel/test_LineOfSight/test_single_plane_los.py
>      LOS_MINIMAL as profiles. with all params in self.kwargs_los set to zero, the results
```suggestion
    LOS_MINIMAL as profiles. With all params in self.kwargs_los set to zero, the results
```

2025-03-08 00:46 UTC, ajshajib commented on test/test_LensModel/test_LineOfSightFlexion/test_single_plane_los_flexion.py
> +    these functions are the same as in TestLensModel but with the addition of LOSF and
```suggestion
    These functions are the same as in TestLensModel but with the addition of LOSF and
```

2025-03-08 00:46 UTC, ajshajib commented on test/test_LensModel/test_LineOfSightFlexion/__init__.py
The relevant tests modules should also be moved accordingly, if the restructuring of the files suggested above is incorporated

2025-03-12 14:41 UTC, nataliehogg commented
hi @ajshajib I think I managed to make all the changes you requested, let us know if there's anything more we should do!

2025-03-12 15:24 UTC, ajshajib commented
Thanks a lot, @nataliehogg! I have made some more restructuring changes, and I will merge after the tests pass.

2025-03-12 16:48 UTC, ajshajib approved these changes

2025-03-12 16:48 UTC, merged

2025-03-12 17:44 UTC, nataliehogg commented
thank you @ajshajib ! :pray: