Time-delay likelihood correction for multiple point sources
lenstronomy/lenstronomy pull request #680
Opened 2024-12-03 10:41 UTC by martin-millon

Solve issue #678. 

Changes : 
- Allows to provide list of list of booleans for each point source and for each image to determine which time-delays are used
- Propagation of the z_lens_convention argument in multiplane 
- Introduce the color bar option in the convergence plot 
- Propagate the lens equation solver options to the point source plots

2024-12-03 13:13 UTC, sibirrer requested changes
Thank you @martin-millon ! I have some comments and questions whether the changes will work with error covariance matrices. I'd still like to have a single boolean per point source model be supported, if possible. 
There is also some text coverage dropping due to mostly small changes in the plotting routine.

2024-12-03 13:13 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +        This list must have the same length as time_delays_measured and time_delays_uncertainties.
for the second line, there should be a space inwards to be rendered properly

2024-12-03 13:13 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +                    raise ValueError(
this error does not seem to be backwards compatible. A single True per point source model should also be possible and then resulting in the delays being calculated and evaluated between all of the point sources

2024-12-03 13:13 UTC, sibirrer commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +                        self._delays_errors[i][mask],
i am not sure this works when providing a n x n covariance matrix as the errors in the delays

2024-12-03 13:26 UTC, martin-millon commented
@sibirrer I am still working on this PR, especially the automated test, which needs to be updated. I'll let you know when it's ready and include your comments in the new version.

2024-12-03 18:07 UTC, martin-millon commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +                        self._delays_errors[i][mask],
This is now tested in L220 of test_time_delay_likelihood.py and it works

2024-12-03 18:07 UTC, martin-millon commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +                    raise ValueError(
It should be backward compatible now

2024-12-03 18:08 UTC, martin-millon commented on lenstronomy/Sampling/Likelihoods/time_delay_likelihood.py
> +        This list must have the same length as time_delays_measured and time_delays_uncertainties.
corrected

2024-12-03 18:08 UTC, martin-millon commented
@sibirrer I think this is now ready to be merged.

2024-12-03 18:12 UTC, sibirrer requested changes
Looks good. Just some minor docstrings to be added and I am waiting for the coverage report

2024-12-03 18:12 UTC, sibirrer commented on lenstronomy/Plots/lens_plot.py
> +    :param with_color_bar: bool, if True, shows color bar
can you add docstrings for colorer_label and font_size?

2024-12-04 09:51 UTC, martin-millon commented
I don't get why these two lines of code do not get executed by codecov whereas the program enters the if statement...

2024-12-04 13:12 UTC, merged