m=1 multipole (spherical/elliptical) + updated solution of m=3 multipole
lenstronomy/lenstronomy pull request #685
Opened 2024-12-09 19:53 UTC by Hadrien-Pgnt

Implements solutions for the spherical m=1, elliptical m=1 and elliptical m=3 that have fully continuous deflection fields (old m=3 version had discontinuities).

2024-12-09 20:58 UTC, dangilman commented
@Hadrien-Pgnt Thanks for adding this! Regarding the tests, the main thing that needs to happen is for the test_numeric_lens_differentials to pass, and for the solutions to match spherical multipoles for q=1. You could probably simplify the test suite to just do those checks

2024-12-10 04:28 UTC, dangilman requested changes
Thanks a lot @Hadrien-Pgnt. Everything looks great, one very minor comment about a line that gets missed by tests, but otherwise it looks good to go

2024-12-10 04:28 UTC, dangilman commented on lenstronomy/LensModel/Profiles/multipole.py
> +        :param m: int, multipole order, m>=&
possible typo in docstring?

2024-12-10 04:28 UTC, dangilman commented on lenstronomy/LensModel/Profiles/multipole.py
> +                f_ = r * np.log(r / r_E) * a_m / 2 * np.cos(phi - phi_m)
I think this line, the m=1 case of the q -> 1 special case, was missed by tests

2024-12-11 02:16 UTC, dangilman approved these changes

2024-12-11 02:17 UTC, merged

2024-12-11 05:23 UTC, Hadrien-Pgnt commented on lenstronomy/LensModel/Profiles/multipole.py
> +                f_ = r * np.log(r / r_E) * a_m / 2 * np.cos(phi - phi_m)
I test that the elliptical solution with q approaching 1 is approximately the spherical solution.
This line is here (for all orders m) to avoid numerical instabilities due to terms (1-q)^(-n) when q is too close to 1, they are copies of the spherical multipole solution - I'll make that explicit in another PR and add a test to check that solutions are exactly the same if the "q too close to 1" condition is verified.